Repository bolt/core, pull requests merged in 2020-02, with the labels that each got.

#1014 Use Bolt Query and remove findForListing
  src/Repository/ContentRepository.php
  src/Twig/RelatedExtension.php
Labels: 🎩 refactor

#1027 Bugfix/fix listing
  src/Controller/Frontend/ListingController.php
  tests/e2e/record_listing.feature
Labels: 🐛 tag: bug fix

#1026 Two fixes for Frontend menus
  src/Menu/FrontendMenuBuilder.php
Labels: 🐛 tag: bug fix

#1053 Implement missing utility functions for widgets
  src/Twig/WidgetExtension.php
  src/Widget/BaseWidget.php
  src/Widgets.php
Labels: new feature

#1058 Implement `isallowed` twig function
  src/Twig/UserExtension.php
Labels: 🐛 tag: bug fix

#1067 Admin panel doesn't break when a collection is removed form contenttypes.yaml
  src/Entity/Field/CollectionField.php
Labels: 🐛 tag: bug fix

#1069 Always show slug in listing title, even if translations are available
  assets/js/app/listing/Components/Table/Row/index.vue
Labels: 🐛 tag: bug fix

#1074 Use || instead of or
  src/Utils/TranslationsManager.php
Labels: tag: enhancement

#1093 Add migrations and `content_id` column to logging table
  composer.json
  config/bundles.php
  config/packages/doctrine_migrations.yaml
  config/services.yaml
  src/Entity/Log.php
  src/Migrations/Version20200219064805.php
Labels: new feature

#1100 Fix/fix paging in backend
  src/Controller/Backend/ContentOverviewController.php
  src/Controller/Frontend/ListingController.php
Labels: 🐛 tag: bug fix

#1099 Only list published content
  src/Controller/Frontend/ListingController.php
Labels: 🐛 tag: bug fix

#1097 Show proper exception when trying to set non-existing Field
  src/Entity/Content.php
Labels: 🐛 tag: bug fix

#1095 Slug and Status are required, but not always set.
  src/Configuration/Parser/ContentTypesParser.php
  src/Entity/Content.php
Labels: 🐛 tag: bug fix

#1098 Make Request optional to allow using Storage\Query in a non-web context
  src/Storage/ContentQueryParser.php
  src/Storage/Handler/SelectQueryHandler.php
Labels: 🐛 tag: bug fix

#1132 Set default status and default values on Record instantiation
  config/bolt/contenttypes.yaml
  src/Entity/Content.php
  templates/_partials/fields/_base.html.twig
Labels: 🐛 tag: bug fix

#1133 If strength == false, make sure it propagates to Vue component
  templates/_partials/fields/password.html.twig
Labels: 🐛 tag: bug fix

#1146 Omit Title in Excerpt by default
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#1147 Allow for adding locales to `config/services.yaml`
  config/packages/translation.yaml
  config/services.yaml
  src/Configuration/Parser/ContentTypesParser.php
  src/Kernel.php
Labels: 🐛 tag: bug fix

#1153 Don't show orphaned content on Dashboard if a ContentType was removed
  src/Controller/Backend/DashboardController.php
  src/Controller/Backend/GeneralController.php
  src/Repository/ContentRepository.php
Labels: 🐛 tag: bug fix
