Repository bolt/core, pull requests merged in 2020-10, with the labels that each got.

#1927 Exclude relations from `Content::toArray()`
  src/Entity/Content.php
Labels: 🐛 tag: bug fix

#1935 Better feedback when `|related` and their ilk fail
  src/Twig/RelatedExtension.php
  templates/_partials/notification.html.twig
Labels: topic: DX

#1940 Backend in Bulgarian / Панел на български 🇧🇬
  config/services.yaml
  translations/messages.bg.xlf
Labels: tag: enhancement, topic: Multilingual 🌐

#1943 Better way to allow `x` in thumbnail URLs alongside `×`
  src/Controller/ImageController.php
Labels: 🍏 low hanging fruit

#1942 Ensure we have an array of records in "select" block
  templates/helpers/_field_blocks.twig
Labels: 🐛 tag: bug fix

#1941 Add missing `json_decode` Twig Filter
  src/Twig/JsonExtension.php
Labels: 🐛 tag: bug fix

#1948 Ensure the "Titles" in collection blocks are plain text only
  assets/js/app/editor/Components/Collection.vue
  assets/scss/modules/editor/fields/_collection.scss
  templates/_partials/fields/_collection_buttons.html.twig
  translations/messages.en.xlf
Labels: 🐛 tag: bug fix

#1946 Delete Version20200219064805.php
  src/Migrations/Version20200219064805.php
Labels: 🧹 Chore

#1933 Initial PostgreSQL support
  .env.dist
  .gitignore
  README.md
  config/packages/doctrine.yaml
  src/Doctrine/Functions/Rand.php
  src/Doctrine/JsonHelper.php
  src/Doctrine/Query/Cast.php
  src/Doctrine/Version.php
  src/Entity/FieldTranslation.php
  src/Entity/Log.php
  src/Repository/ContentRepository.php
  src/Storage/Directive/OrderDirective.php
  src/Storage/Directive/RandomDirectiveHandler.php
  src/Storage/SelectQuery.php
  templates/helpers/_field_blocks.twig
Labels: new feature

#1952 Allow default values for Fields in new Content
  templates/_partials/fields/_base.html.twig
Labels: 🍏 low hanging fruit

#1955 Ignore empty like `%%` parameters
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#1954 Access extensions by name with full namespace
  src/Extension/ExtensionRegistry.php
Labels: 🐛 tag: bug fix

#1962 Feature/translations russian
  translations/messages.ru.xlf
  translations/security.ru.xlf
  translations/validators.ru.xlf
Labels: new feature

#1964 Use `id` in `{% setcontent %}` for Select in Blocks
  templates/helpers/_field_blocks.twig
Labels: 🧹 Chore

#1963 🧹 Cleanup for `Doctrine\Version`
  src/Doctrine/Version.php
Labels: 🧹 Chore

#1970 Simplified Chinese translation
  translations/messages.zh_CN.xlf
  translations/security.zh_CN.xlf
  translations/validators.zh_CN.xlf
Labels: new feature, topic: Multilingual 🌐

#1968 Redirect to record or new record on singleton listing pages in backend
  src/Controller/Backend/ListingController.php
Labels: 🐛 tag: bug fix

#1983 Fix url for 'bulk' operations on Listing screen, for sites with modified Backend URL
  assets/js/app/listing/Components/SelectBox.vue
  templates/content/listing.html.twig
Labels: 🐛 tag: bug fix

#1987 Any field that has a localized field down the line is considered localized
  src/Configuration/Parser/ContentTypesParser.php
  src/Entity/FieldParentTrait.php
Labels: 🐛 tag: bug fix

#1988 Deprecate `default_state` for collection in favour of `variant`
  assets/js/app/editor/Components/Collection.vue
  config/bolt/contenttypes.yaml
  templates/_partials/fields/collection.html.twig
Labels: 🎩 refactor

#1989 A little less padding on lists in Cards
  assets/scss/init/_base.scss
Labels: 🧹 Chore

#2003 Don't break if slug is `null` as opposed to "empty string"
  assets/js/app/listing/Components/Table/Row/_Actions.vue
  assets/js/app/listing/Components/Table/Row/index.vue
Labels: 🐛 tag: bug fix

#2004 Updating the system font stack for 2020
  assets/scss/init/_variables.scss
  public/theme/skeleton/css/new.css
  templates/_partials/notification.html.twig
Labels: 🧹 Chore

#2009 Update readme (remove beta reference)
  README.md
Labels: 🧹 Chore

#2011 Don't repeat "Add to collection" text when there's only one
  assets/js/app/editor/Components/Collection.vue
Labels: 🐛 tag: bug fix

#2008 Filter by any field
  src/Controller/Backend/ListingController.php
  src/Controller/TwigAwareController.php
  templates/content/listing.html.twig
  translations/messages.en.xlf
Labels: new feature

#2015 Enable twig namespace 'theme' by default
  config/packages/twig.yaml
Labels: 🧹 Chore

#2006 Prepare release 4.1.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2020 Update .gitattributes. We most certainly _do_ want `/assets/static`
  .gitattributes
Labels: 🐛 tag: bug fix

#2022 Put back some more files that we really do need.
  .gitattributes
Labels: 🐛 tag: bug fix

#2026 Show set as block
  assets/scss/modules/editor/fields/_set.scss
  assets/scss/modules/editor/fields/fields.scss
  templates/_partials/fields/_base.html.twig
  templates/_partials/fields/set.html.twig
Labels: 🐛 tag: bug fix

#2032 Multivalue querying does not break for taxonomies
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#2033 Prepare release 4.1.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/Version.php
  symfony.lock
Labels: 🧹 Chore

#2007 Refactoring Login Form to Symfony Forms
  src/Controller/Backend/AuthenticationController.php
  src/Form/LoginType.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/security/login.html.twig
  tests/behat/bootstrap/WebContext.php
  tests/e2e/edit_record_1.feature
  tests/e2e/login.feature
  tests/e2e/record_localization.feature
  translations/messages.en.xlf
Labels: tag: enhancement, 🎩 refactor

#2034 Add Greek EL translations
  translations/messages.el.xlf
  translations/security.el.xlf
  translations/validators.el.xlf
Labels: new feature, topic: Multilingual 🌐

#2037 Preserve user's chosen locale in Editor
  src/Controller/Backend/UserEditController.php
  src/Event/Subscriber/LocaleSubscriber.php
  src/Event/Subscriber/UserLocaleSubscriber.php
  src/Event/UserEvent.php
Labels: topic: Multilingual 🌐, 🐛 tag: bug fix

#2043 Fix PHPStan breaking on `url_decode`
  src/Twig/TextExtension.php
Labels: 🧹 Chore

#2048 Fix PHPstan breakage
  .travis.yml
  phpstan.neon
Labels: 🧹 Chore

#2055 Keep track of assets version on "About" page
  assets/js/app/common.js
  assets/js/version.js
  package-lock.json
  package.json
  templates/pages/about.html.twig
Labels: new feature

#2056 Add `Carbon` to `scanDirectories`
  phpstan.neon
Labels: topic: DX

#2058 Prepare release 4.1.4
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2063 Cleaning up `composer.json`
  composer.json
Labels: 🧹 Chore

#2074 Access `defaultLocale` in twig
  config/packages/twig.yaml
Labels: tag: enhancement

#2076 Add three more 'allowed' tags by default
  config/bolt/config.yaml
Labels: 🍏 low hanging fruit, 🧹 Chore

#2072 Remove extraneous whitespace in excerpts
  composer.json
  src/Twig/ContentExtension.php
  src/Utils/Excerpt.php
  src/Utils/Html.php
Labels: 🐛 tag: bug fix

#2068 Make "files" selector use more levels
  src/Controller/Backend/Async/FileListingController.php
Labels: 🍏 low hanging fruit, 🐛 tag: bug
