Repository bolt/core, pull requests merged in 2020-08, with the labels that each got.

#1671 Don't output common Fields twice (in "block output helper")
  src/Repository/FieldRepository.php
  templates/helpers/_field_blocks.twig
  templates/helpers/_fields.twig
Labels: 🐛 tag: bug fix

#1674 Some minor code improvements
  src/Api/Extensions/ContentExtension.php
  src/Command/ExtensionsConfigureCommand.php
  src/Doctrine/Version.php
Labels: 🧹 Chore

#1673 Child fields can render html by default, without |raw filter
  src/Entity/Field.php
Labels: 🐛 tag: bug fix

#1677 Deprecate `translated` filter in favour of `translate`
  src/Twig/TranslatableExtension.php
Labels: 🎩 refactor

#1685 Show detailed localization for fields containing subfields
  templates/content/view_locales.html.twig
Labels: new feature

#1688 Fix menu `item|current` in _menu.html.twig
  templates/helpers/_menu.html.twig
Labels: 🐛 tag: bug fix

#1692 Thumbnailing works with only width or only height
  src/Utils/ThumbnailHelper.php
Labels: 🐛 tag: bug fix

#1691 Allow textarea `height` option
  assets/js/app/editor/Components/Textarea.vue
  config/bolt/contenttypes.yaml
  src/Configuration/Content/FieldType.php
  templates/_partials/fields/textarea.html.twig
  tests/php/Configuration/Parser/ContentTypesParserTest.php
Labels: new feature

#1694 Feature/orderby taxonomies
  public/theme/skeleton/custom/setcontent_1.twig
  src/Storage/Directive/OrderDirective.php
  src/Storage/QueryInterface.php
  src/Storage/SelectQuery.php
Labels: new feature

#1695 Optimise `selected` filter to fetch records with a single DB call
  src/Twig/FieldExtension.php
Labels: tag: enhancement, 🎩 refactor

#1686 Set user status, confirm user delete, select scalar value
  assets/js/app/editor/Components/Select.vue
  src/Controller/Backend/UserEditController.php
  templates/users/edit.html.twig
  templates/users/listing.html.twig
  tests/e2e/users.feature
Labels: tag: enhancement

#1689 Localize submenu buttons
  assets/js/app/sidebar/Components/Menu/_SubMenu.vue
  assets/js/app/sidebar/Components/Menu/index.vue
  assets/js/app/sidebar/Components/Sidebar.vue
  templates/_base/layout.html.twig
  tests/e2e/edit_record_1.feature
  tests/e2e/record_listing.feature
  translations/messages.en.xlf
  translations/validators.en.xlf
Labels: 🐛 tag: bug fix

#1701 Use embed without `raw` filter
  src/Entity/Field/EmbedField.php
Labels: tag: enhancement

#1702 Refactor relations to be properly bidirectional
  src/Entity/Relation.php
  src/Factory/RelationFactory.php
  src/Repository/RelationRepository.php
  src/Twig/RelatedExtension.php
Labels: 🎩 refactor

#1699 Improve Sanitiser. Sanitise fields on save.
  config/bolt/config.yaml
  config/services.yaml
  src/Configuration/Parser/GeneralParser.php
  src/Entity/Field/CheckboxField.php
  src/Entity/Field/CollectionField.php
  src/Entity/Field/FileField.php
  src/Entity/Field/FilelistField.php
  src/Entity/Field/HiddenField.php
  src/Entity/Field/ImageField.php
  src/Entity/Field/ImagelistField.php
  src/Entity/Field/RawPersistable.php
  src/Entity/Field/SelectField.php
  src/Entity/Field/SetField.php
  src/Event/Listener/FieldFillListener.php
  src/Utils/Sanitiser.php
Labels: 🐛 tag: bug fix

#1704 Allow for `variant: inline` for most fields
  templates/_partials/fields/_base.html.twig
Labels: new feature, 🍏 low hanging fruit

#1705 Pager uses default listing records, if available.
  src/Controller/Frontend/ListingController.php
  src/Twig/ContentExtension.php
Labels: tag: enhancement

#1709 Output Fields correctly, when using the Fields Block
  composer.json
  src/Twig/FieldExtension.php
  templates/helpers/_fields.twig
Labels: 🐛 tag: bug fix

#1717 No longer lock ECS, make it work as intended again
  composer.json
  ecs.php
  src/Entity/Field.php
  symfony.lock
Labels: 🧹 Chore

#1710 Enforce unique slugs
  config/services.yaml
  src/Event/Listener/ContentFillListener.php
  src/Repository/FieldRepository.php
  tests/e2e/edit_record_1.feature
Labels: new feature

#1723 add Slug field UTF-8 and Transliteration Support
  assets/js/filters/string.js
  tests/php/Menu/FrontendMenuBuilderTest.php
Labels: tag: enhancement, topic: Vue

#1726 Remove services before `composer remove`
  composer.json
  src/Command/ExtensionsConfigureCommand.php
Labels: 🐛 tag: bug fix

#1731 Fix ECS 😅
  ecs.php
Labels: topic: DX

#1730 Set filter in "Templateselect" to a regex by default
  config/bolt/contenttypes.yaml
  src/Twig/ContentExtension.php
Labels: 🍏 low hanging fruit

#1733 Make multivalue filter with content fields
  public/theme/skeleton/custom/setcontent_1.twig
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#1737 Current filter works for locale
  src/Twig/CommonExtension.php
Labels: new feature

#1736 Remove `JSON_CONTAINS` from `doctrine.yaml`
  config/packages/doctrine.yaml
Labels: 🍏 low hanging fruit

#1735 Rename renderTemplate to render for consistency with AbstractController
  src/Controller/Backend/AuthenticationController.php
  src/Controller/Backend/ContentEditController.php
  src/Controller/Backend/ContentLocalizationController.php
  src/Controller/Backend/DashboardController.php
  src/Controller/Backend/DatabaseIntegrityController.php
  src/Controller/Backend/FileEditController.php
  src/Controller/Backend/FilemanagerController.php
  src/Controller/Backend/FixturesController.php
  src/Controller/Backend/GeneralController.php
  src/Controller/Backend/ListingController.php
  src/Controller/Backend/LogViewerController.php
  src/Controller/Backend/MediaController.php
  src/Controller/Backend/MediaEditController.php
  src/Controller/Backend/MenuPageController.php
  src/Controller/Backend/OmnisearchController.php
  src/Controller/Backend/ProfileController.php
  src/Controller/Backend/UserController.php
  src/Controller/Backend/UserEditController.php
  src/Controller/Frontend/ListingController.php
  src/Controller/Frontend/SearchController.php
  src/Controller/Frontend/TaxonomyController.php
  src/Controller/Frontend/TemplateController.php
  src/Controller/TwigAwareController.php
Labels: 🎩 refactor

#1738 New `page` directive for setcontent to override the current page setting
  public/theme/skeleton/custom/setcontent_1.twig
  src/Storage/ContentQueryParser.php
  src/Storage/Directive/PageDirective.php
  src/Storage/Handler/SelectQueryHandler.php
  src/Twig/TokenParser/SetcontentTokenParser.php
  tests/php/Twig/SetcontentTokenParserTest.php
Labels: new feature

#1742 Add "Number" and "Date" fields
  templates/helpers/_field_blocks.twig
Labels: 🐛 tag: bug fix

#1759 Prevent breakage when trying to excerpt a Field
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#1756 Add "Article" and "Redactor" to contentfixtures
  src/DataFixtures/ContentFixtures.php
Labels: 🧹 Chore

#1760 Bugfix/support db without json
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#1761 Allow collections to include extension fields
  templates/_macro/_macro.html.twig
Labels: 🐛 tag: bug fix

#1763 `localdate` uses prefers currentlocale over defaultlocale
  src/Twig/LocaleExtension.php
Labels: tag: enhancement

#1766 Fix: Correctly exclude fields that are used in the slug by default
  templates/helpers/_fields.twig
Labels: 🐛 tag: bug fix

#1768 Date field required updates validity when set
  assets/js/app/common.js
  assets/js/app/editor/Components/Date.vue
Labels: 🐛 tag: bug fix

#1765 Fall back to "dumb" numeric sorting for older SQLite versions
  src/Storage/Directive/OrderDirective.php
Labels: 🐛 tag: bug fix

#1773 Test/db supports json
  public/theme/skeleton/custom/setcontent_1.twig
Labels: topic: Tests

#1776 Better check for `INSTR` and `CAST`
  public/theme/skeleton/custom/setcontent_1.twig
  src/Doctrine/Version.php
  src/Storage/Directive/OrderDirective.php
Labels: topic: Tests, 🐛 tag: bug fix

#1771 Unsplash images fixtures work even if ssl verification fails
  config/bolt/config.yaml
  src/Configuration/Parser/GeneralParser.php
  src/DataFixtures/ImageFetchFixtures.php
Labels: 🐛 tag: bug fix

#1774 Fix orderby non-localizable field in localized contenttype
  src/Storage/Directive/OrderDirective.php
Labels: 🐛 tag: bug fix

#1777 Localehelper shouldn't break on CLI commands
  src/Utils/LocaleHelper.php
Labels: 🍏 low hanging fruit

#1778 Numeric order works on MySQL databases
  config/packages/doctrine.yaml
  src/Doctrine/Version.php
  src/Entity/Field/NumberField.php
  src/Storage/Directive/OrderDirective.php
Labels: 🐛 tag: bug fix

#1779 Update `config.yaml` with documentation on curl options.
  README.md
  config/bolt/config.yaml
Labels: 🧹 Chore

#1780 Prepare release 4.0.0-rc.38
  CHANGELOG.md
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#1781 Get curl_options as an array instead of collection
  src/DataFixtures/ImageFetchFixtures.php
Labels: 🐛 tag: bug fix

#1782 Filter and order using queryparams on listing pages
  config/bolt/config.yaml
  src/Configuration/Parser/GeneralParser.php
  src/Controller/Frontend/ListingController.php
  src/Storage/Handler/SelectQueryHandler.php
Labels: new feature

#1783 Prepare release 4.0.0-rc.39
  CHANGELOG.md
  config/bolt/config.yaml
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#1786 Avoid caching slug uses definition for new records
  src/Entity/Field/SlugField.php
  templates/_partials/fields/slug.html.twig
Labels: 🐛 tag: bug fix

#1792 Preparing release 4.0.0-rc.40
  CHANGELOG.md
  assets/scss/modules/editor/_label.scss
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore
