Repository bolt/core, pull requests merged in 2020-01, with the labels that each got.

#846 Fix Templateselect showing up as JSON
  src/Entity/Field/TemplateselectField.php
Labels: 🐛 tag: bug fix

#874 Add our own TranslationInterface
  phpstan.neon
  src/Entity/FieldTranslation.php
  src/Entity/TranslationInterface.php
Labels: 🐛 tag: bug fix

#872 Update `findOneByFieldValue` method to handle translated fields
  src/Repository/ContentRepository.php
Labels: 🐛 tag: bug fix

#888 Generate `services_bolt.yaml` file, so that extensions can be used as services
  config/services_bolt.yaml
  src/Extension/ExtensionCompilerPass.php
  src/Extension/ExtensionRegistry.php
  src/Kernel.php
Labels: new feature, topic: Extensions

#902 Resolve Z-index issue in file manager
  assets/scss/layout/_admin.scss
  assets/scss/modules/admin/_sidebar.scss
Labels: topic: UX, 🐛 tag: bug fix

#920 Enhancement/more structured tests
  README.md
  assets/js/app/editor/Components/File.vue
  assets/js/app/editor/Components/Image.vue
  behat.yml
  composer.json
  run_behat_tests.sh
  tests/api/bootstrap/FeatureContext.php
  tests/api/get_content.feature
  tests/api/get_content_fields.feature
  tests/behat/bootstrap/ApiContext.php
  tests/behat/bootstrap/CommonContext.php
  tests/behat/bootstrap/WebContext.php
  tests/behat/edit_record_1.feature
  tests/e2e/README.md
  tests/e2e/backend_api.feature
  tests/e2e/backend_translations.feature
  tests/e2e/dashboard.feature
  tests/e2e/display_listing.feature
  tests/e2e/display_record.feature
  tests/e2e/display_record_test.feature
  tests/e2e/display_search.feature
  tests/e2e/display_taxonomies.feature
  tests/e2e/edit_record_1.feature
  tests/e2e/edit_record_2.feature
  tests/e2e/extension_routing.feature
  tests/e2e/filemanager.feature
  tests/e2e/frontend_menu.feature
  tests/e2e/homepage.feature
  tests/e2e/kitchensink.feature
  tests/e2e/login.feature
  tests/e2e/record_listing.feature
  tests/e2e/setcontent.feature
  tests/e2e/users.feature
  tests/e2e/widgets.feature
Labels: topic: Tests, 🎩 refactor

#922 Bugfix/datetime picker
  assets/scss/modules/editor/fields/_date.scss
Labels: 🐛 tag: bug fix

#924 Persist collection items correctly
  src/Utils/TranslationsManager.php
  templates/_partials/fields/_base.html.twig
Labels: 🐛 tag: bug fix

#975 Get the first imagefield that actually has an image in it
  src/Twig/ContentExtension.php
Labels: 🍏 low hanging fruit, 🐛 tag: bug fix
