Repository bolt/core, pull requests merged in 2020-09, with the labels that each got.

#1799 shouldreturnsingle handles id filtering based on operator
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#1800 Fix breakage in PROD for `type: select` fields
  src/Controller/Backend/ContentEditController.php
  src/Entity/Content.php
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#1795 Include taxonomy types if no taxonomies set
  public/theme/skeleton/partials/_sub_taxonomylinks.twig
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#1801 Minor fix: Set database path correctly
  src/Configuration/PathResolver.php
Labels: 🍏 low hanging fruit, 🐛 tag: bug fix

#1806 Allow for more control over formatting of prefix and postfix
  assets/scss/modules/editor/fields/_pre_postfix.scss
  config/bolt/contenttypes.yaml
  templates/_partials/fields/_base.html.twig
  tests/e2e/kitchensink.feature
Labels: topic: CSS/SCSS/Styling

#1809 Make order filter work with `ContentHelper::get()` options
  public/theme/skeleton/custom/setcontent_1.twig
  src/Twig/ArrayExtension.php
Labels: 🐛 tag: bug fix

#1812 Update `UnderscoreNamingStrategy` in `doctrine.yaml`
  config/packages/doctrine.yaml
Labels: topic: DX

#1814 Don't list Singletons ContentTypes in Aside
  public/theme/skeleton/partials/_aside.twig
Labels: 🐛 tag: bug fix

#1813 Fall back to `DetailController` when trying to "list" a Singleton ContentType
  src/Controller/Frontend/ListingController.php
Labels: 🐛 tag: bug fix

#1811 Fix `Notice: Array to string conversion` in `Field.php` by ensuring the array is one level deep.
  src/Entity/Field.php
Labels: 🐛 tag: bug fix

#1815 Fix deprecation in RouteCollectionBuilder
  src/Kernel.php
Labels: 🧹 Chore

#1820 Allow src in iframes for embeds to work. Add spinner feedback while embed is loading.
  assets/js/app/editor/Components/Embed.vue
  src/Utils/Sanitiser.php
Labels: 🐛 tag: bug fix

#1804 Run tests in prod
  .travis.yml
  config/bundles.php
  config/packages/security_checker.yaml
Labels: topic: DX, topic: Tests

#1822 Don't break if we're trying to get content for "no ContentTypes"
  src/Storage/Query.php
Labels: 🐛 tag: bug fix

#1823 Search without author returns results
  src/Repository/ContentRepository.php
Labels: 🐛 tag: bug fix

#1827 Prevent recursion in `title_format`
  src/Utils/ContentHelper.php
  src/Utils/Recursion.php
Labels: 🐛 tag: bug fix

#1826 Listing singleton uses `record_route` setting
  src/Controller/Frontend/ListingController.php
Labels: tag: enhancement

#1828 Add pattern `url` and `email` options as shown in the docs
  src/Configuration/Parser/ContentTypesParser.php
Labels: 🐛 tag: bug fix

#1824 Clear menu caches on content delete. Log delete event.
  src/Event/Subscriber/ContentSaveSubscriber.php
Labels: 🐛 tag: bug fix

#1829 Listing search uses correct config. Add `--like` option to query params search
  src/Controller/Frontend/ListingController.php
Labels: 🐛 tag: bug fix

#1831 Use `travis_retry` command on frequently failing behat tests
  .travis.yml
Labels: topic: Tests

#1832 Update `_taxonomylinks.html.twig`: fix link
  templates/helpers/_taxonomylinks.html.twig
Labels: 🍏 low hanging fruit

#1835 Imagelists and Filelists work in collections
  .travis.yml
  assets/js/app/editor/Components/Filelist.vue
  assets/js/app/editor/Components/Imagelist.vue
  ecs.php
  templates/helpers/_taxonomylinks.html.twig
Labels: 🐛 tag: bug fix

#1836 Update top toolbar. Kill your darlings!
  assets/js/app/toolbar/Components/Toolbar.vue
  assets/scss/modules/admin/_toolbar.scss
  package-lock.json
  package.json
  templates/_base/layout.html.twig
Labels: topic: CSS/SCSS/Styling

#1838 Support taxonomies in `title_format` and `excerpt_format`
  src/Utils/ContentHelper.php
Labels: 🐛 tag: bug fix

#1830 Collapsible collections
  assets/js/app/editor/Components/Collection.vue
  assets/scss/modules/editor/fields/_collection.scss
  assets/scss/modules/editor/fields/fields.scss
  config/bolt/contenttypes.yaml
  src/Configuration/Content/FieldType.php
  templates/_macro/_macro.html.twig
  templates/_partials/fields/_base.html.twig
  templates/_partials/fields/_collection_buttons.html.twig
  templates/_partials/fields/collection.html.twig
  tests/e2e/edit_record_1.feature
  tests/php/Configuration/Parser/ContentTypesParserTest.php
  translations/messages.en.xlf
Labels: new feature

#1840 Make `placeholders()` accept `null` for robustness
  src/Twig/HtmlExtension.php
Labels: 🍏 low hanging fruit

#1839 Deprecate use of Symfony 4
  composer.json
Labels: dependencies

#1841 Add `fixture_format` option to fields
  config/bolt/contenttypes.yaml
  src/DataFixtures/ContentFixtures.php
Labels: new feature, topic: Content

#1844 Make possible to check if an extension is present, directly in Twig
  src/Command/ExtensionsListCommand.php
  src/Twig/ExtensionExtension.php
Labels: new feature

#1846 Updating Fixtures for impending release
  config/bolt/config.yaml
  src/DataFixtures/ContentFixtures.php
  src/DataFixtures/ImageFetchFixtures.php
Labels: 🍏 low hanging fruit

#1845 Add optional parameter to `excerpt` to wrap output in `<p>`
  src/Twig/ContentExtension.php
Labels: new feature, 🍏 low hanging fruit

#1851 Fix ECS by explicitly skipping `UnaryOperatorSpacesFixer`
  ecs.php
Labels: 🧹 Chore

#1853 No dropdown for adding collection items if there's just one.
  assets/js/app/editor/Components/Collection.vue
  templates/_partials/fields/collection.html.twig
  translations/messages.en.xlf
Labels: tag: enhancement

#1854 Re-enable `composer validate --strict` in CI
  .travis.yml
Labels: 🧹 Chore

#1856 Allow multiple roles to be selected for users
  assets/js/app/editor/Components/Password.vue
  src/Controller/Backend/UserEditController.php
  templates/_partials/fields/select.html.twig
  templates/users/edit.html.twig
Labels: 🐛 tag: bug fix

#1859 Don't break if editor tries editing a record with a missing definition
  src/Configuration/Content/ContentType.php
  templates/content/edit.html.twig
  translations/messages.en.xlf
Labels: tag: enhancement

#1855 [WIP] Re-run behat tests on clean plate in case they fail mid-test
  .travis.yml
  Makefile
Labels: 🧹 Chore

#1862 Fix phpstan break (again)!
  phpstan.neon
Labels: 🧹 Chore

#1861 Slugs in fixtures use the `uses:` attribute to make sensible slugs
  src/DataFixtures/ContentFixtures.php
Labels: 🐛 tag: bug fix

#1864 Update about page with Symfony 5
  templates/pages/about.html.twig
Labels: 🧹 Chore

#1866 Configure homepage without a record or listing
  src/Controller/Frontend/HomepageController.php
Labels: new feature

#1865 Allow up to 120 characters on a line of JS code
  .eslintrc.js
  assets/js/app/editor/Components/Collection.vue
  assets/js/app/editor/Components/Date.vue
  assets/js/app/editor/Components/Embed.vue
  assets/js/app/editor/Components/File.vue
  assets/js/app/editor/Components/Filelist.vue
  assets/js/app/editor/Components/Html.vue
  assets/js/app/editor/Components/Image.vue
  assets/js/app/editor/Components/Imagelist.vue
  assets/js/app/editor/Components/Markdown.vue
  assets/js/app/editor/Components/Password.vue
  assets/js/app/editor/Components/Select.vue
  assets/js/app/editor/Components/Slug.vue
  assets/js/app/editor/Components/ThemeSelect.vue
  assets/js/app/listing/Components/Filter.vue
  assets/js/app/listing/Components/SelectBox.vue
  assets/js/app/listing/Components/Table/Row/_Actions.vue
  assets/js/app/listing/Components/Table/Row/_Checkbox.vue
  assets/js/app/listing/Components/Table/Row/_Meta.vue
  assets/js/app/listing/Components/Table/Row/index.vue
  assets/js/app/listing/Components/Table/index.vue
  assets/js/app/patience-is-a-virtue.js
  assets/js/app/sidebar/Components/Menu/_SubMenu.vue
  assets/js/app/sidebar/Components/Menu/index.vue
  assets/js/app/sidebar/Components/Sidebar.vue
  assets/js/app/sidebar/Components/_SidebarToggler.vue
  assets/js/app/toolbar/Components/Toolbar.vue
  assets/js/filters/date.js
  assets/js/filters/string.js
  assets/js/services/api/content.js
  assets/js/vibrant.js
Labels: 🎩 refactor

#1867 Ensure config for `not_found` etc. are arrays. (and some cleanup of old, deprecrated stuff)
  config/bolt/config.yaml
  src/Configuration/Parser/GeneralParser.php
  src/Utils/Html.php
Labels: 🐛 tag: bug fix

#1872 Don't show `Media created successfully` if it's not new
  src/Controller/Backend/MediaEditController.php
Labels: 🐛 tag: bug fix

#1870 Edit attributes button does not break the page.
  templates/_partials/fields/textarea.html.twig
Labels: 🐛 tag: bug fix

#1879 Adding `base-2021` to `CopyThemesCommand`
  src/Command/CopyThemesCommand.php
Labels: 🧹 Chore

#1885 Minor fix: Check if `Content` is set in preview mode.
  src/Entity/Field.php
Labels: 🐛 tag: bug fix

#1884 Allow numeric slugs with `allow_numeric` attribute in ContentType
  config/bolt/contenttypes.yaml
  src/Controller/Frontend/DetailController.php
  src/Entity/Field/SlugField.php
Labels: new feature

#1893 Fix "zero width spaces" and Twigified titles in backend.
  src/Entity/Field.php
  templates/_partials/fields/_base.html.twig
Labels: 🐛 tag: bug fix

#1890 Fix Z-index, attempt 2
  assets/scss/vendor/multiselect.scss
Labels: 🐛 tag: bug fix

#1896 Only show "Preview" button if ContentType is not Viewless
  templates/content/_buttons.html.twig
Labels: 🐛 tag: bug fix

#1901 Getting a date uses the default timezone from config
  src/Configuration/Parser/GeneralParser.php
  src/Twig/FieldExtension.php
  src/Twig/LocaleExtension.php
Labels: 🐛 tag: bug fix

#1897 Prepare release 4.0.0
  CHANGELOG.md
  assets/js/app/listing/Components/Table/Row/_Actions.vue
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#1908 Cleanup, this is handled in ENV / Doctrine
  src/Configuration/Parser/GeneralParser.php
Labels: 🧹 Chore

#1922 Fix: Don't break when passing in params for "Search Query"
  config/bolt/config.yaml
  ecs.php
  src/Controller/Frontend/ListingController.php
  src/Storage/SelectQuery.php
  src/Twig/TokenParser/SetcontentTokenParser.php
Labels: 🐛 tag: bug fix

#1925 Empty image Field should return `null` instead of `files/`
  src/Entity/Field/FileExtrasTrait.php
  src/Entity/Field/FileField.php
  src/Entity/Field/ImageField.php
Labels: 🐛 tag: bug fix
