Repository bolt/core, pull requests merged in 2020-03, with the labels that each got.

#1191 Don't break when trying to write thumbnails to non-writable folder
  src/Controller/ImageController.php
Labels: 🐛 tag: bug fix

#1195 Sorting correctly for MySQL
  config/bolt/contenttypes.yaml
  src/Configuration/Parser/ContentTypesParser.php
  src/Controller/Backend/ListingController.php
  src/Controller/Frontend/ListingController.php
  src/Storage/Directive/OrderDirective.php
  tests/php/Configuration/Parser/ContentTypesParserTest.php
Labels: 🐛 tag: bug fix

#1196 Set permissions on created files correctly (as configured)
  config/bolt/config.yaml
  src/Command/CopyAssetsCommand.php
  src/Command/CopyThemesCommand.php
  src/Controller/ImageController.php
Labels: new feature

#1209 Fix/show on dashboard
  src/Configuration/Parser/ContentTypesParser.php
  src/Controller/Backend/DashboardController.php
  src/Controller/Frontend/SearchController.php
  src/Repository/ContentRepository.php
  tests/php/Configuration/Parser/ContentTypesParserTest.php
Labels: 🐛 tag: bug fix

#1212 Don't fill placeholders for ImageField if filename is not set.
  src/Entity/Field/ImageField.php
Labels: 🐛 tag: bug fix

#1210 Make `show_in_menu` work as expected
  src/Menu/BackendMenuBuilder.php
  translations/messages.en.xlf
Labels: new feature

#1211 Don't show slugs for contenttypes without slugs
  src/Configuration/Content/FieldType.php
  src/Configuration/Parser/ContentTypesParser.php
  src/Entity/Content.php
  templates/content/_fields.html.twig
  tests/php/Configuration/Parser/ContentTypesParserTest.php
Labels: 🐛 tag: bug fix

#1233 Don't break when trying to save a file that's not writable
  src/Controller/Backend/FileEditController.php
  templates/finder/editfile.html.twig
  translations/messages.en.xlf
Labels: 🐛 tag: bug fix

#1234 Allow for taxonomy listings with singular Taxonomy Type slug
  src/Configuration/Config.php
  src/Controller/Frontend/TaxonomyController.php
Labels: 🐛 tag: bug fix

#1236 Image URL uses canonical config setting and take imagelist into account for the magic image
  src/Canonical.php
  src/Entity/Field/ImageField.php
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#1235 `postfix` and `prefix` need `display: block`
  assets/scss/modules/editor/fields/_pre_postfix.scss
Labels: 🐛 tag: bug fix

#1232 Make `required` work as expected.
  assets/js/app/editor/Components/Select.vue
  config/bolt/taxonomy.yaml
  package-lock.json
  package.json
  src/Configuration/Parser/TaxonomyParser.php
  src/Entity/Content.php
  src/Entity/Field/SelectField.php
  src/Entity/User.php
  src/Twig/ContentExtension.php
  src/Twig/RelatedExtension.php
  templates/_partials/fields/_base.html.twig
  templates/_partials/fields/_label.html.twig
  templates/_partials/fields/select.html.twig
  templates/_partials/fields/templateselect.html.twig
  templates/content/_fields_aside.html.twig
  templates/content/_relationships.html.twig
  templates/content/_taxonomies.html.twig
  templates/users/edit.html.twig
  templates/users/profile.html.twig
  tests/e2e/users.feature
  tests/php/Configuration/Parser/TaxonomyParserTest.php
Labels: 🐛 tag: bug fix

#1238 Allow `where` filtering on taxonomies in `setcontent`
  src/Storage/Directive/PrintQueryDirective.php
  src/Storage/Handler/SelectQueryHandler.php
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#1245 Access fields inside a set by their name
  src/Entity/Field/SetField.php
Labels: 🐛 tag: bug
