Repository bolt/core, pull requests merged in 2020-12, with the labels that each got.

#2202 Use `setcontent` to filter with checkbox `true` or `false`
  src/Doctrine/JsonHelper.php
  src/Storage/QueryParameterParser.php
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#2198 Allow `id` in sanitiser (purifier). Don't sanitise fields with `sanitise: false`
  src/Event/Listener/FieldFillListener.php
  src/Utils/Sanitiser.php
Labels: 🐛 tag: bug fix

#2204 Introduce `viewless_listing` setting in addition to `viewless` for Record detail pages
  src/Api/Extensions/ContentExtension.php
  src/Configuration/Parser/ContentTypesParser.php
  src/Controller/Frontend/ListingController.php
  tests/php/Configuration/Parser/ContentTypesParserTest.php
Labels: new feature

#2147 Show 'quick links' to taxonomies in the sidebar of listings
  assets/scss/modules/base/_badges.scss
  src/Controller/Backend/ListingController.php
  templates/content/listing.html.twig
  translations/messages.en.xlf
Labels: new feature

#2207 Fix homepage link generation, generate fallbacks as relative unless canonical
  src/Canonical.php
  src/Utils/ContentHelper.php
Labels: 🐛 tag: bug fix

#2193 Set defaults for avatar settings
  src/Configuration/Parser/GeneralParser.php
Labels: 🐛 tag: bug fix

#2203 Don't break with `TaxonomyRepository::factory() must be of the type string, int given`
  src/Controller/Backend/ContentEditController.php
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#2211 Ensure `selected` filter returns record if set to `multiple: false`
  src/Configuration/Parser/ContentTypesParser.php
Labels: 🐛 tag: bug fix

#2209 Create Welcome command
  src/Command/WelcomeCommand.php
Labels: new feature

#2226 Fix failing `/** @var mixed */` ECS check
  src/Storage/QueryParameterParser.php
Labels: topic: Tests

#2227 Run E2E tests on lowest supported PHP version only [new features]
  .github/workflows/behavioural_tests.yaml
Labels: topic: Tests, 🧹 Chore

#2228 Run E2E tests on lowest supported PHP version only [bugfixes]
  .github/workflows/behavioural_tests.yaml
Labels: topic: Tests, 🧹 Chore

#2237 Deprecate `bolt/binary-chromedriver` for `lanfest/binary-chromedriver`
  composer.json
Labels: dependencies

#2236 Show the user avatar in the toolbar, if it exists
  assets/js/app/toolbar/Components/Toolbar.vue
  templates/_base/layout.html.twig
Labels: tag: enhancement

#2235 `|svg` filter uses correct path inside collection/set
  src/Twig/ImageExtension.php
Labels: 🐛 tag: bug fix

#2230 Fix issue with sorting order for `|selected`
  src/Twig/FieldExtension.php
Labels: 🐛 tag: bug fix

#2231 Show correct timezone for Content dates (createdAt, modifiedAt, publishedAt, depublishedat)
  src/Entity/Content.php
Labels: 🐛 tag: bug fix

#2240 Don't break if a set's definition no longer contains a field
  src/Controller/Backend/ContentEditController.php
Labels: 🐛 tag: bug fix

#2246 Support tailwind pager for base-2021
  templates/helpers/_pager_tailwind.html.twig
Labels: 🐛 tag: bug fix

#2242 Update symfony.lock
  composer.json
  package-lock.json
  package.json
  symfony.lock
Labels: 🧹 Chore

#2243 Prepare release 4.1.9
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2232 Prepare migrations for 4.2
  composer.json
  config/bundles.php
  config/packages/doctrine_migrations.yaml
  migrations/.gitignore
  migrations/Version20201210105836.php
  symfony.lock
Labels: 🚸 Migration

#2233 Warn of outstanding migrations
  bin/composer-script/post-update-cmd.php
  bin/composer-script/run.php
Labels: 🚸 Migration

#2255 Don't sanitise markdown fields
  src/Entity/Field/MarkdownField.php
Labels: 🐛 tag: bug fix

#2254 Pager `Previous` and `Next` are localized labels. `active` state for basic pager.
  templates/helpers/_pager_basic.html.twig
  templates/helpers/_pager_bulma.html.twig
  templates/helpers/_pager_tailwind.html.twig
Labels: 🐛 tag: bug fix

#2256 Make the migrations conditional
  migrations/Version20201210105836.php
Labels: 🚸 Migration

#2266 Fix escaping of ContentType names in listing pages
  templates/content/listing.html.twig
Labels: 🐛 tag: bug fix

#2264 Set `base-2020` in `GeneralParser.php`
  src/Configuration/Parser/GeneralParser.php
Labels: 🐛 tag: bug fix
