Repository bolt/core, pull requests merged in 2020-06, with the labels that each got.

#1429 Fix collections visibility
  src/Controller/Backend/ContentEditController.php
  src/Entity/Field.php
  src/Entity/Field/CollectionField.php
  src/Entity/Field/SetField.php
  src/Entity/FieldParentInterface.php
  src/Entity/FieldParentTrait.php
  src/Utils/TranslationsManager.php
Labels: 🐛 tag: bug fix

#1434 Localize collections with easier contenttype config
  src/Entity/FieldParentInterface.php
  src/Entity/FieldParentTrait.php
Labels: tag: enhancement

#1441 Remove locale setting from bolt config (legacy)
  config/bolt/config.yaml
Labels: 🧹 Chore

#1439 Fix htmllang() when no locales defined
  src/Utils/LocaleHelper.php
Labels: 🐛 tag: bug fix

#1433 Remove old field types
  config/bolt/contenttypes.yaml
  src/Entity/Field/GeolocationField.php
  src/Entity/Field/VideoField.php
  tests/e2e/edit_record_2.feature
Labels: 🧹 Chore

#1448 Fix for windows not handling `%k` in timestamp strings properly
  templates/_macro/_macro.html.twig
  templates/_partials/fields/date.html.twig
  templates/content/_buttons.html.twig
  templates/users/listing.html.twig
Labels: 🐛 tag: bug fix

#1449 Prepare release 4.0.0-rc.23
  CHANGELOG.md
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#1451 Better check for `isSpecialPage` if `homepage:` is set to a contenttype (listing)
  src/Controller/Frontend/HomepageController.php
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#1456 Fix ObjectManager namespace for fixtures (phpstan complaining)
  src/DataFixtures/ContentFixtures.php
  src/DataFixtures/ImageFetchFixtures.php
  src/DataFixtures/ImagesFixtures.php
  src/DataFixtures/RelationsFixtures.php
  src/DataFixtures/TaxonomyFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: 🧹 Chore

#1455 Make sure list field |length filter works as expected
  src/Entity/Field/CollectionField.php
  src/Entity/Field/FileField.php
  src/Entity/Field/FilelistField.php
  src/Entity/Field/ImageField.php
  src/Entity/Field/ImagelistField.php
  src/Entity/Field/SetField.php
  src/Entity/ListFieldInterface.php
  src/Entity/ListFieldTrait.php
Labels: 🐛 tag: bug fix

#1469 Fix excerpt length
  src/Utils/Html.php
Labels: 🐛 tag: bug fix

#1468 Update `getContentTypeName()`, add `getContentTypeSingularName()`
  config/bolt/config.yaml
  src/Entity/Content.php
  src/Event/Listener/ContentFillListener.php
Labels: 🐛 tag: bug fix

#1480 Two more deprecations fixed!
  src/Event/Subscriber/CheckRequirementsSubscriber.php
  src/Twig/ContentExtension.php
Labels: 🧹 Chore

#1481 Sort multiselect fields with drag and drop
  assets/js/app/editor/Components/Select.vue
  assets/scss/modules/editor/fields/_multiselect.scss
  assets/scss/modules/editor/fields/fields.scss
Labels: new feature

#1471 Display the Set field correctly in the Editor when new field is added after saving record
  src/Controller/Backend/ContentEditController.php
  src/Entity/Field/SetField.php
  templates/_partials/fields/set.html.twig
Labels: 🐛 tag: bug fix

#1479 Fix capitalisation in groups
  composer.json
  src/Twig/TextExtension.php
  templates/content/_tabs.html.twig
Labels: 🐛 tag: bug fix

#1485 Make Collection Field properly Iterable
  src/Entity/Field/CollectionField.php
  src/Entity/Field/CollectionFieldIteratorTrait.php
  src/Entity/Field/FilelistField.php
  src/Entity/Field/ImagelistField.php
  src/Entity/Field/SetField.php
  src/Entity/ListFieldTrait.php
Labels: 🐛 tag: bug fix

#1494 Fix Imagelist alt 'true' issue. Clean up Vue components
  assets/js/app/editor/Components/Image.vue
  assets/js/app/editor/Components/Imagelist.vue
  package.json
  templates/_partials/fields/image.html.twig
Labels: 🐛 tag: bug fix

#1491 Include homepage record in Twig globals
  src/Controller/Frontend/DetailController.php
  src/Controller/Frontend/HomepageController.php
Labels: 🐛 tag: bug fix

#1495 Better check for maximum filesize
  src/Controller/Backend/Async/UploadController.php
Labels: 🐛 tag: bug fix

#1497 Fix: Don't show spinners on invalid form submissions
  assets/js/app/patience-is-a-virtue.js
Labels: 🐛 tag: bug fix

#1499 Fix current locale to be correct
  src/Utils/LocaleHelper.php
Labels: 🐛 tag: bug fix

#1484 Add ability to override routing with record_route
  src/Canonical.php
  src/Configuration/Parser/ContentTypesParser.php
  src/Repository/ContentRepository.php
  src/Twig/ContentExtension.php
  tests/php/Configuration/Parser/ContentTypesParserTest.php
Labels: new feature

#1502 Tests/twig
  src/Repository/FieldRepository.php
  src/Twig/ContentExtension.php
  tests/php/Twig/ContentExtensionTestCase.php
  tests/php/Twig/FieldExtensionTestCase.php
  tests/php/Twig/TextExtensionTestCase.php
Labels: topic: Tests

#1505 Placeholder in Image Field is not clickable if empty
  assets/js/app/editor/Components/Image.vue
Labels: 🐛 tag: bug fix

#1508 Small cleanup of dashboard search test
  tests/e2e/dashboard_globalsearch.feature
Labels: topic: Tests, 🧹 Chore

#1519 Sort Bundles.php alphabetically
  config/bundles.php
Labels: 🧹 Chore

#1520 Make sure sets inside collections are instantiated with actual values
  src/Event/Listener/FieldFillListener.php
  templates/_partials/fields/image.html.twig
Labels: 🐛 tag: bug fix

#1521 Datefield uses global app to access user locale
  templates/_partials/fields/date.html.twig
Labels: 🐛 tag: bug fix

#1526 Don't "warm up" cache on `composer update`, to save time and prevent dreaded `ProcessTimedOutException` after 10 seconds..
  composer.json
Labels: 🐛 tag: bug fix

#1527 Ensure `$boltConfig` is set for Controllers in extensions
  src/Extension/ExtensionController.php
  src/Extension/ServicesTrait.php
Labels: 🐛 tag: bug fix

#1518 Cleanup usage of `$request` in Controllers (since TwigAwareController already has it)
  src/Controller/Backend/Async/EmbedController.php
  src/Controller/Backend/Async/FileListingController.php
  src/Controller/Backend/Async/UploadController.php
  src/Controller/Backend/BulkOperationsController.php
  src/Controller/Backend/ContentEditController.php
  src/Controller/Backend/ContentLocalizationController.php
  src/Controller/Backend/FileEditController.php
  src/Controller/Backend/FilemanagerController.php
  src/Controller/Backend/LogViewerController.php
  src/Controller/Backend/MediaEditController.php
  src/Controller/Backend/ProfileController.php
  src/Controller/Backend/UserEditController.php
  src/Controller/CsrfTrait.php
  src/Controller/FileController.php
  src/Controller/Frontend/ListingController.php
  src/Controller/Frontend/SearchController.php
  src/Controller/Frontend/TaxonomyController.php
  src/Controller/ImageController.php
  src/Controller/TwigAwareController.php
  src/TemplateChooser.php
Labels: topic: DX

#1516 Localization tests for saved changes in different locales
  tests/e2e/edit_record_2.feature
Labels: topic: Tests

#1531 [WIP] Warn editors about file upload errors
  assets/js/app/editor/Components/File.vue
  assets/js/app/editor/Components/Image.vue
Labels: tag: enhancement, topic: UX

#1529 Use currently rendered locale in OrderDirective
  src/Storage/ContentQueryParser.php
  src/Storage/Directive/OrderDirective.php
  src/Storage/FrontendQueryScope.php
  src/Twig/LocaleExtension.php
  src/Utils/LocaleHelper.php
Labels: 🐛 tag: bug fix

#1500 Use Friends of Behat Behat for Symfony 5
  behat.yml
  composer.json
  config/bundles.php
  symfony.lock
Labels: 🎩 refactor, 🧹 Chore

#1545 After adding `symfony/proxy-manager-bridge`, table prefix went missing
  config/bundles.php
  config/services_test.yaml
  src/Doctrine/TablePrefix.php
  src/Doctrine/TablePrefixTrait.php
  symfony.lock
Labels: 🐛 tag: bug fix

#1548 Make sure contenttypes routes are updated after changes to contenttypes.yaml
  src/Configuration/Config.php
  src/Controller/Backend/ClearCacheController.php
  tests/php/Configuration/ConfigTest.php
Labels: 🐛 tag: bug fix

#1550 Better UI for dragging in multiselect
  assets/js/app/editor/Components/Select.vue
  assets/scss/modules/editor/fields/_multiselect.scss
Labels: tag: enhancement, topic: UX

#1549 Allow "Homepage" to be in viewless ContentType
  src/Configuration/Config.php
  src/Controller/Frontend/HomepageController.php
Labels: 🐛 tag: bug fix

#1562 Fix issue with undefined index 0 for a select field inside a a set
  src/Controller/Backend/ContentEditController.php
Labels: 🐛 tag: bug fix

#1565 Singletons return single Content result with `{% setcontent %}`
  src/Controller/TwigAwareController.php
  src/Storage/ContentQueryParser.php
  src/Storage/Directive/ReturnMultipleDirective.php
  src/Storage/Handler/IdentifiedSelectHandler.php
  src/Storage/Handler/LatestQueryHandler.php
  src/Storage/Handler/SelectQueryHandler.php
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#1570 Cache clear does not loop in Config
  src/Configuration/Config.php
Labels: 🐛 tag: bug fix

#1569 Add defaultlocale to duplicate action twig
  src/Controller/Backend/ContentEditController.php
Labels: 🐛 tag: bug fix

#1572 Include proper css for file uploader
  assets/scss/vendor/dropzone.scss
  assets/scss/vendor/vendor.scss
Labels: 🐛 tag: bug fix

#1573 Save content on ctrl+s and cmd+s
  assets/js/app/index.js
  assets/js/app/save-on-ctrl-s.js
  package-lock.json
  package.json
  templates/content/_buttons.html.twig
  templates/media/edit.html.twig
  templates/users/edit.html.twig
  templates/users/profile.html.twig
Labels: new feature

#1574 Slug regenerates on duplicate
  src/Controller/Backend/ContentEditController.php
  templates/_partials/fields/slug.html.twig
Labels: 🐛 tag: bug fix

#1576 Re-set `setSingleFetchMode` to ensure returning a pager, if needed
  src/DataFixtures/ContentFixtures.php
  src/Storage/Handler/SelectQueryHandler.php
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#1577 Prepare release 4.0.0-rc.27
  CHANGELOG.md
  package.json
  src/Version.php
Labels: 🧹 Chore
