Repository bolt/core, pull requests merged in 2020-07, with the labels that each got.

#1580 Paginate users listing
  src/Controller/Backend/UserController.php
  templates/users/listing.html.twig
Labels: new feature

#1582 Don't break line on date field with valueonly
  templates/_partials/fields/date.html.twig
Labels: 🐛 tag: bug fix

#1592 Use `taxonomy|link` filter to get taxonomy links
  public/theme/skeleton/partials/_sub_taxonomylinks.twig
  src/Entity/Taxonomy.php
  src/Twig/ContentExtension.php
Labels: tag: enhancement

#1591 Use humanized taxonomy name when creating new taxonomies
  src/Repository/TaxonomyRepository.php
Labels: 🐛 tag: bug fix

#1594 Make sure form validation works with `data-patience` buttons
  assets/js/app/patience-is-a-virtue.js
Labels: 🐛 tag: bug fix

#1598 Sorry GitHub Actions 😢 you are breaking too often
  .github/workflows/code_checks.yaml
Labels: 🧹 Chore

#1595 `setcontent` returns single for contenttype/id
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#1586 Display Symfony version in "About" and `bolt:info` screens
  src/Command/InfoCommand.php
  src/Controller/Backend/GeneralController.php
  src/Version.php
  templates/pages/about.html.twig
Labels: topic: DX

#1599 Refactor `setcontent` handles and directives
  public/theme/skeleton/custom/setcontent_1.twig
  public/theme/skeleton/partials/_aside.twig
  src/Storage/ContentQueryParser.php
  src/Storage/Directive/EarliestDirectiveHandler.php
  src/Storage/Directive/GetQueryDirective.php
  src/Storage/Directive/LatestDirectiveHandler.php
  src/Storage/Directive/LimitDirective.php
  src/Storage/Directive/OffsetDirective.php
  src/Storage/Directive/OrderDirective.php
  src/Storage/Directive/PrintQueryDirective.php
  src/Storage/Directive/ReturnMultipleDirective.php
  src/Storage/Directive/ReturnSingleDirective.php
  src/Storage/Handler/FirstQueryHandler.php
  src/Storage/Handler/LatestQueryHandler.php
  src/Twig/TokenParser/SetcontentTokenParser.php
  tests/php/Twig/SetcontentTokenParserTest.php
Labels: 🎩 refactor, 🧨 breaking change

#1601 Chore: Updating NPM dependencies
  package-lock.json
  package.json
Labels: 🧹 Chore

#1602 Allow "focus" parameter for excerpts of plain strings
  src/Twig/ContentExtension.php
Labels: new feature

#1606 Add random directive to setcontent tag
  config/packages/doctrine.yaml
  src/Doctrine/Functions/Rand.php
  src/Storage/ContentQueryParser.php
  src/Storage/Directive/EarliestDirectiveHandler.php
  src/Storage/Directive/OffsetDirective.php
  src/Storage/Directive/RandomDirectiveHandler.php
  src/Twig/TokenParser/SetcontentTokenParser.php
Labels: new feature

#1612 Put `localedatetime` with previous format and deprecated notice. Use `localdate` with new format
  src/Twig/LocaleExtension.php
  templates/_macro/_macro.html.twig
  templates/_partials/fields/date.html.twig
Labels: 🐛 tag: bug fix

#1611 Add `getuser` with alias `user` Twig function
  src/Twig/UserExtension.php
Labels: new feature

#1621 Allow optional space in QueryParameterParser between operand and keyword
  src/Storage/QueryParameterParser.php
Labels: 🐛 tag: bug fix

#1616 Order by number field
  composer.json
  config/packages/doctrine.yaml
  phpstan.neon
  public/theme/skeleton/custom/setcontent_1.twig
  src/DataFixtures/ContentFixtures.php
  src/Storage/Directive/OrderDirective.php
Labels: 🐛 tag: bug fix

#1623 Prepare release 4.0.0-rc.29
  CHANGELOG.md
  package-lock.json
  package.json
  src/Version.php
  symfony.lock
Labels: 🧹 Chore

#1618 Users extension prep
  config/services.yaml
  src/Controller/Backend/ContentEditController.php
  src/Controller/Backend/UserEditController.php
  src/Controller/ErrorController.php
  src/Controller/Frontend/DetailController.php
  src/Controller/Frontend/DetailControllerInterface.php
  src/Controller/Frontend/HomepageController.php
  src/Controller/Frontend/ListingController.php
  src/Controller/Frontend/SearchController.php
  src/Controller/Frontend/TaxonomyController.php
  src/Controller/TwigAwareController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Enum/UserStatus.php
  src/Event/UserEvent.php
  src/Extension/ExtensionCompilerPass.php
  src/Security/LoginFormAuthenticator.php
  src/Security/UserChecker.php
  src/Twig/ContentExtension.php
  templates/users/listing.html.twig
Labels: tag: enhancement, 🧨 breaking change

#1628 Richer content format option
  assets/js/app/editor/Components/Select.vue
  src/Twig/ContentExtension.php
  src/Twig/RelatedExtension.php
  src/Utils/ContentHelper.php
Labels: tag: enhancement

#1629 Make empty multiselect tag invisible
  assets/js/app/editor/Components/Select.vue
  assets/scss/modules/editor/fields/_multiselect.scss
Labels: 🐛 tag: bug fix

#1630 Fix `setcontent` random directive to override anything else set by the OrderDirective
  public/theme/skeleton/custom/setcontent_1.twig
  src/Storage/Directive/RandomDirectiveHandler.php
Labels: 🐛 tag: bug fix

#1635 [WIP] Add support for "403 Forbidden" pages
  assets/scss/modules/base/_status.scss
  config/bolt/config.yaml
  src/Controller/ErrorController.php
  src/DataFixtures/ContentFixtures.php
  src/Twig/ContentExtension.php
  src/Utils/ContentHelper.php
Labels: new feature

#1633 Shuffle paginated records
  phpstan.neon
  public/theme/skeleton/custom/setcontent_1.twig
  src/Twig/ArrayExtension.php
Labels: 🐛 tag: bug fix

#1639 We were a bit overzealous in removing the compilerpass. Turns out we _do_ need `packages/bolt.yaml`
  composer.json
  config/packages/bolt.yaml
  config/packages/extension_reference-extension.yaml
  config/routes/extension_reference-extension.yaml
  config/services_bolt.yaml
  src/Command/ExtensionsConfigureCommand.php
  src/Extension/ExtensionCompilerPass.php
  src/Kernel.php
  symfony.lock
Labels: 🐛 tag: bug fix

#1648 Make Sanitiser obey allowed tags and attributes from `config.yaml`
  composer.json
  src/Entity/ContentExtrasTrait.php
  src/Entity/Field.php
  src/Twig/ContentExtension.php
  src/Utils/Sanitiser.php
  symfony.lock
Labels: 🐛 tag: bug fix

#1647 Allow for custom `500 Internal Server Error` pages.
  config/bolt/config.yaml
  src/Controller/ErrorController.php
  templates/helpers/page_403.html.twig
  templates/helpers/page_500.html.twig
Labels: new feature

#1646 Update htaccess, according to SF 5 defaults
  public/.htaccess
Labels: 🧹 Chore

#1645 Pass on Query parameters to subrequest from Homepage
  src/Controller/Frontend/HomepageController.php
Labels: 🐛 tag: bug fix

#1649 Allow for extensions to add new FieldTypes
  src/Configuration/Content/FieldType.php
  templates/content/_fields.html.twig
  templates/helpers/_field_blocks.twig
Labels: new feature

#1656 Allow extensions to have an `install` method, which is called on installation (to install assets, for example)
  src/Command/ExtensionsConfigureCommand.php
Labels: new feature

#1659 [WIP] Use `current` filter to check if menu item is this page
  public/theme/skeleton/partials/_sub_menu.twig
  public/theme/skeleton/partials/_sub_menu_header.twig
  src/Configuration/Parser/MenuParser.php
  src/Twig/CommonExtension.php
  src/Twig/ContentExtension.php
  src/Twig/FrontendMenuExtension.php
  tests/php/Configuration/Parser/MenuParserTest.php
  tests/php/Menu/FrontendMenuBuilderTest.php
Labels: 🐛 tag: bug fix

#1661 `svg` filter outputs raw svg file
  src/Twig/ImageExtension.php
Labels: new feature

#1662 Fix set field being localizable
  src/Controller/Backend/ContentEditController.php
Labels: 🐛 tag: bug fix

#1667 FieldRepository::factory can instantiate Extension fields
  src/Repository/FieldRepository.php
Labels: tag: enhancement

#1668 Add image.extension value
  src/Controller/ImageController.php
  src/Entity/Field/FileExtrasTrait.php
  src/Entity/Field/FileField.php
  src/Entity/Field/ImageField.php
  tests/api/get_content.feature
Labels: tag: enhancement
