Repository bolt/core, pull requests merged in 2020-11, with the labels that each got.

#2083 Don't break installation if SQLite is not present
  src/Command/InfoCommand.php
Labels: 🐛 tag: bug fix

#2091 Fix empty Imagelist breaking rendering in Prod ENV
  templates/_partials/fields/imagelist.html.twig
Labels: 🐛 tag: bug fix

#2098 Searchable relations
  assets/js/app/editor/Components/Select.vue
  templates/content/_relationships.html.twig
Labels: new feature

#2093 Correctly instantiate fields in prod
  src/Kernel.php
  src/Repository/FieldRepository.php
  src/Twig/FieldExtension.php
Labels: 🐛 tag: bug fix

#2096 Show filelist and imagelist in a card
  assets/scss/modules/editor/fields/_as_card.scss
  assets/scss/modules/editor/fields/fields.scss
  templates/_partials/fields/_base.html.twig
Labels: tag: enhancement

#2105 Explicitly set `form_theme` for when a project defines its own forms.
  templates/security/login.html.twig
Labels: 🐛 tag: bug fix

#2107 Show preview button on Homepage, even if viewless
  src/Twig/ContentExtension.php
  templates/content/_buttons.html.twig
Labels: 🐛 tag: bug fix

#2108 Configure extension config on install and update + more output when something fails
  bin/composer-script/post-install-cmd.php
  bin/composer-script/post-update-cmd.php
  bin/composer-script/run.php
Labels: 🐛 tag: bug fix

#2106 Copy link to clipboard in filemanager
  assets/js/app/common.js
  assets/scss/init/_base.scss
  templates/finder/_files_actions.html.twig
  translations/messages.en.xlf
Labels: new feature

#2111 Replace Faker with fork, since original is abandoned
  composer.json
  symfony.lock
Labels: 🧹 Chore

#2118 Bugfix incorrect `|current` filter for localized menu items
  src/Entity/Content.php
  src/Utils/ContentHelper.php
Labels: 🐛 tag: bug fix

#2110 Fix: in `getTaxonomies()`, return early when we don't have "Content"
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#2121 Fix excessive padding in dropdowns
  assets/scss/init/_base.scss
  assets/scss/modules/admin/_widgets.scss
Labels: 🐛 tag: bug fix

#2133 add additional labels
  translations/messages.ru.xlf
Labels: tag: enhancement

#2139 Use correct template directory in templateselect
  src/Configuration/Parser/ThemeParser.php
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#2140 Show field label inside collection
  assets/js/app/editor/Components/Collection.vue
Labels: 🐛 tag: bug fix

#2137 `|selected` filter orders by the value of the select
  src/Twig/FieldExtension.php
Labels: 🐛 tag: bug fix

#2138 Set inside set displays properly
  templates/_partials/fields/set.html.twig
Labels: 🐛 tag: bug fix

#2146 Fix: Set a default status for the `default_status`
  src/Entity/Content.php
Labels: 🐛 tag: bug fix

#2149 Add comment explaining how the orderByNumericField() internals work, …
  src/Storage/Directive/OrderDirective.php
Labels: 🧹 Chore

#2163 Merging mishap: This shouldn't have been in this branch
  assets/js/app/editor/Components/Select.vue
Labels: 🐛 tag: bug fix

#2164 Release/4.1.7
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2167 Fix searchable relations
  assets/js/app/editor/Components/Select.vue
Labels: 🐛 tag: bug fix

#2166 Make Forgot password button less prominent than login
  templates/security/login.html.twig
Labels: 🐛 tag: bug fix

#2169 Move 'Forgot password' link to the right
  templates/security/login.html.twig
Labels: 🐛 tag: bug fix

#2172 Checkbox value can be unset
  assets/js/app/editor/Components/Checkbox.vue
  assets/js/app/editor/index.js
  src/Entity/Field/CheckboxField.php
  templates/_partials/fields/checkbox.html.twig
Labels: 🐛 tag: bug fix

#2173 Allow '/' in setcontent where query
  src/Storage/QueryParameterParser.php
Labels: 🐛 tag: bug fix

#2183 delete controllers that only rendered the 'placeholder' template
  src/Controller/Backend/FixturesController.php
  src/Controller/Backend/OmnisearchController.php
Labels: 🧹 Chore

#2186 Sort templateselect alphabetically
  src/Twig/ContentExtension.php
Labels: tag: enhancement

#2189 Fix for Argument 1 passed to Bolt\Repository\FieldRepository::findAllBySlug() must be of the type string, null given
  src/DataFixtures/ContentFixtures.php
  src/Event/Listener/ContentFillListener.php
Labels: 🐛 tag: bug fix

#2195 Allow omitting of `generator` meta tag and `x-powered-by` header
  config/bolt/config.yaml
  src/Configuration/Parser/GeneralParser.php
  src/Event/Subscriber/WidgetSubscriber.php
Labels: new feature

#2196 Prepare release `4.1.8`
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
Labels: 🧹 Chore

#2194 Set the Version to `4.2 beta 1`
  src/Version.php
Labels: 🧹 Chore

#2197 Prepare Release `4.1.8`
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2187 Deprecate Travis CI => GitHub Actions
  .github/workflows/behavioural_tests.yaml
  .github/workflows/unit_tests.yaml
  .travis.yml
  README.md
Labels: 🧹 Chore

#2199 update Checkbox.vue to remove "-->" unexpected line
  package-lock.json
Labels: 🐛 tag: bug fix
