Repository bolt/core, pull requests merged in 2020-05, with the labels that each got.

#1350 Updating some Easy Coding Standards settings
  easy-coding-standard.yml
  src/Command/AddUserCommand.php
  src/Command/CopyAssetsCommand.php
  src/Command/CopyThemesCommand.php
  src/Command/DeleteUserCommand.php
  src/Command/ExtensionsShowCommand.php
  src/Command/ImageTrait.php
  src/Command/ResetSecretCommand.php
  src/Configuration/Parser/ContentTypesParser.php
  src/Configuration/Parser/GeneralParser.php
  src/Configuration/PathResolver.php
  src/Controller/Backend/Async/UploadController.php
  src/Controller/Backend/BulkOperationsController.php
  src/Controller/Backend/ContentEditController.php
  src/Controller/Backend/ExtensionsController.php
  src/Controller/Backend/FileEditController.php
  src/Controller/Backend/FilemanagerController.php
  src/Controller/Backend/UserEditController.php
  src/Controller/TwigAwareController.php
  src/DataFixtures/BaseFixture.php
  src/DataFixtures/ContentFixtures.php
  src/Doctrine/TablePrefix.php
  src/Entity/Content.php
  src/Entity/Field.php
  src/Entity/Field/EmbedField.php
  src/Entity/Field/FileExtrasTrait.php
  src/Entity/FieldTranslation.php
  src/Entity/Log.php
  src/Entity/Media.php
  src/Entity/Relation.php
  src/Entity/Taxonomy.php
  src/Entity/User.php
  src/Entity/UserAuthToken.php
  src/Event/Subscriber/MaintenanceModeSubscriber.php
  src/Extension/ExtensionRegistry.php
  src/Factory/MediaFactory.php
  src/Menu/CachedBackendMenuBuilder.php
  src/Repository/ContentRepository.php
  src/Repository/LogRepository.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  src/Storage/ContentQueryParser.php
  src/Storage/Directive/OrderDirective.php
  src/Twig/ArrayExtension.php
  src/Twig/ContentExtension.php
  src/Twig/RelatedExtension.php
  src/Twig/WidgetExtension.php
  src/Utils/ComposeValueHelper.php
  src/Utils/Html.php
  src/Utils/LocaleHelper.php
  src/Widget/BaseWidget.php
  src/Widget/CacheTrait.php
  src/Widget/Injector/HtmlInjector.php
  src/Widget/RequestTrait.php
  src/Widget/ResponseTrait.php
  src/Widget/TwigTrait.php
  tests/php/Configuration/Parser/ParserTestBase.php
Labels: topic: DX

#1348 Adding the new Changelog!
  CHANGELOG.md
Labels: topic: DX

#1352 Improve `title_format` and add `excerpt_format` attribute in ContentTypes
  config/bolt/contenttypes.yaml
  src/Configuration/Parser/ContentTypesParser.php
  src/Twig/ContentExtension.php
  src/Utils/ComposeValueHelper.php
Labels: new feature

#1353 Bugfix/collections default fix
  config/services.yaml
  src/Entity/Content.php
  src/Entity/Field.php
  src/Entity/Field/CollectionField.php
  src/Event/Listener/ContentFillListener.php
  src/Event/Listener/FieldFillListener.php
  src/Repository/FieldRepository.php
  templates/_partials/fields/collection.html.twig
Labels: 🎩 refactor, 🐛 tag: bug fix, 🧹 Chore

#1364 Update README - Note about `var/data/bolt.sqlite`
  README.md
Labels: 📙 tag: documentation

#1366 Return correct exit status for cache:thumbs, bolt:reset-secret and bolt:info
  src/Command/ClearThumbnailCacheCommand.php
  src/Command/InfoCommand.php
  src/Command/ResetSecretCommand.php
Labels: 🎩 refactor

#1362 Feature/set default
  config/bolt/contenttypes.yaml
  src/Controller/Backend/ContentEditController.php
  src/DataFixtures/ContentFixtures.php
  src/Entity/Field/CollectionField.php
  src/Entity/Field/EmailField.php
  src/Entity/Field/SetField.php
  src/Entity/FieldParentTrait.php
  src/Event/Listener/ContentFillListener.php
  src/Event/Listener/FieldFillListener.php
  src/Repository/FieldRepository.php
  tests/e2e/edit_record_1.feature
Labels: 🐛 tag: bug fix

#1367 Files extras tests
  config/bolt/contenttypes.yaml
  public/theme/skeleton/custom/test.twig
  src/DataFixtures/ContentFixtures.php
  tests/e2e/display_record_test.feature
Labels: topic: Tests

#1368 Refactor required attribute to be bool, not int
  assets/js/app/editor/Components/Date.vue
  assets/js/app/editor/Components/Email.vue
  assets/js/app/editor/Components/Embed.vue
  assets/js/app/editor/Components/File.vue
  assets/js/app/editor/Components/Image.vue
  assets/js/app/editor/Components/Number.vue
  assets/js/app/editor/Components/Slug.vue
  assets/js/app/editor/Components/Text.vue
  assets/js/app/editor/Components/Textarea.vue
  templates/_partials/fields/_base.html.twig
Labels: 🎩 refactor

#1377 Don't fail on 'Textarea' when it exists
  tests/e2e/edit_record_1.feature
Labels: topic: DX

#1376 NPM Updates, fixing tests
  package-lock.json
  package.json
  tests/e2e/edit_record_1.feature
Labels: 🧹 Chore

#1380 Composer dep updates
  config/bundles.php
  symfony.lock
Labels: 🧹 Chore

#1384 Persist non-translatable field with correct default locale
  src/Configuration/Config.php
  src/Configuration/Content/FieldType.php
  src/Configuration/Parser/ContentTypesParser.php
  src/Entity/Content.php
  src/Entity/Field.php
  src/Event/Listener/ContentFillListener.php
  src/Kernel.php
  src/Repository/FieldRepository.php
  tests/php/Configuration/ConfigTest.php
  tests/php/Configuration/Parser/ContentTypesParserTest.php
Labels: 🐛 tag: bug fix

#1387 Use selenium and chromedriver as composer dev dependencies
  .travis.yml
  Makefile
  README.md
  composer.json
  run_behat_tests.sh
  tests/e2e/README.md
Labels: topic: Tests, 🧹 Chore

#1388 View saved version in current edit locale
  templates/content/_buttons.html.twig
Labels: 🐛 tag: bug fix

#1385 Format title works without breaking on new content. Sorting content by title uses format_title.
  config/bolt/contenttypes.yaml
  public/theme/skeleton/custom/test.twig
  src/Configuration/Parser/ContentTypesParser.php
  src/Storage/Directive/OrderDirective.php
  src/Twig/ContentExtension.php
  src/Twig/RelatedExtension.php
  src/Utils/ContentHelper.php
  templates/content/listing.html.twig
  tests/e2e/display_record_test.feature
Labels: 🎩 refactor, 🐛 tag: bug fix

#1386 Break slightly less when adding new contenttypes
  public/theme/skeleton/partials/_aside.twig
  templates/content/_buttons.html.twig
Labels: 🐛 tag: bug fix

#1391 Add Configuration Notices extension
  composer.json
  config/extensions/bobdenotter-configurationnotices.yaml
  config/services_bolt.yaml
  src/Extension/ServicesTrait.php
Labels: new feature

#1392 Minor CSS changes, update Symfony Encore
  assets/scss/init/_base.scss
  assets/scss/init/_variables.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: dependencies

#1393 Add todo to stop selenium server process
  Makefile
Labels: 🧹 Chore

#1396 Wrap list fields with 1 element in array
  src/Entity/Field.php
  src/Entity/Field/FilelistField.php
  src/Entity/Field/ImagelistField.php
  src/Entity/ListFieldInterface.php
Labels: 🐛 tag: bug

#1397 Get taxonomy by slug
  src/Configuration/Config.php
Labels: tag: enhancement

#1401 Working on Skeleton Theme (New.css instead of Sakura)
  public/theme/skeleton/css/new.css
  public/theme/skeleton/css/normalize.css
  public/theme/skeleton/css/sakura.css
  public/theme/skeleton/partials/_aside.twig
  public/theme/skeleton/partials/_header.twig
  public/theme/skeleton/partials/_image.twig
  public/theme/skeleton/partials/_master.twig
  public/theme/skeleton/partials/_sub_menu_header.twig
  public/theme/skeleton/search.twig
Labels: topic: 🎨 design

#1403 Updates for skeleton theme
  public/theme/skeleton/README.md
  public/theme/skeleton/css/new.css
  symfony.lock
Labels: topic: 🎨 design

#1405 Prepare release 4.0.0 RC 20
  CHANGELOG.md
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#1412 Make sure you can iterate over collection with one field
  src/Entity/Field/CollectionField.php
Labels: 🐛 tag: bug fix

#1411 Allow x as well as × in thumbail URLs
  src/Controller/ImageController.php
Labels: 🐛 tag: bug fix

#1413 Update file listing screen: Lazy loading, paginator, other improvements
  assets/js/app/listing/Components/Table/Row/index.vue
  assets/scss/modules/base/_tables.scss
  assets/scss/modules/base/base.scss
  assets/scss/modules/listing/row/row.scss
  src/Controller/Backend/FilemanagerController.php
  templates/finder/_files_cards.html.twig
  templates/finder/_files_list.html.twig
  templates/finder/_folders.html.twig
  templates/finder/finder.html.twig
  tests/e2e/filemanager.feature
  translations/messages.de.xlf
  translations/messages.en.xlf
  translations/messages.nl.xlf
Labels: 🐛 tag: bug fix

#1416 Add `composer/package-versions-deprecated`
  composer.json
  config/bundles.php
  symfony.lock
Labels: 🧹 Chore

#1419 Image and File fields support twig empty test
  src/Entity/Content.php
  src/Entity/Field/FileField.php
  src/Entity/Field/ImageField.php
Labels: new feature

#1421 Pretty record|link when localization is enabled
  src/Canonical.php
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#1424 Save non-localizable in correct default locale
  src/Controller/Backend/ContentEditController.php
Labels: 🐛 tag: bug fix

#1418 Allow for parsed dates like "Today" or "in 3 weeks"
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#1414 Adding spinners and disabling buttons to indicate the user might have to wait a few seconds
  assets/js/app/editor/Components/File.vue
  assets/js/app/editor/Components/Image.vue
  assets/js/app/index.js
  assets/js/app/listing/Components/Table/Row/_Actions.vue
  assets/js/app/patience-is-a-virtue.js
  assets/js/app/sidebar/Components/Menu/_SubMenu.vue
  templates/content/_buttons.html.twig
  templates/content/listing.html.twig
Labels: topic: UX

#1425 Unescape Vue input fields
  assets/js/app/editor/Components/Text.vue
  assets/js/app/editor/Components/Textarea.vue
  assets/js/app/editor/mixins/value.js
  assets/js/helpers/mixins/fieldValue.js
Labels: 🐛 tag: bug fix

#1426 Don't show Fields that were removed from the ContentType definition
  src/Entity/Content.php
Labels: 🐛 tag: bug fix
