Repository bolt/core, pull requests merged in 2021-03, with the labels that each got.

#2448 Update `shivammathur/setup-php` to v2
  .github/workflows/behavioural_tests.yaml
  .github/workflows/code_analysis.yaml
  .github/workflows/unit_tests.yaml
Labels: topic: Tests

#2449 Update `shivammathur/setup-php` to v2 for accessibility
  .github/workflows/a11y_tests.yaml
  .github/workflows/behavioural_tests.yaml
  .github/workflows/code_analysis.yaml
  .github/workflows/unit_tests.yaml
Labels: topic: Tests

#2447 Order collections by their fields' sortorder
  src/Entity/Field/CollectionField.php
  src/Event/Listener/FieldFillListener.php
Labels: 🐛 tag: bug fix

#2452 Don't break when creating a field with definition inconsistencies
  src/Configuration/Content/FieldType.php
Labels: 🐛 tag: bug fix

#2454 Identical record slugs in `menu.yaml` don't create conflicting URIs
  src/Menu/FrontendMenuBuilder.php
Labels: 🐛 tag: bug fix

#2461 Temporary version lock for `api-platform` bug
  composer.json
Labels: dependencies

#2459 Run yaml migrations on `composer update`
  bin/composer-script/PostUpdateScript.php
Labels: 🐛 tag: bug fix

#2460 Set correct classes and disabled states for the `_pager_basic.html.twig` pager
  templates/helpers/_pager_basic.html.twig
Labels: 🐛 tag: bug fix

#2463 Ensure `slug` has a `uses` set
  src/Configuration/Parser/ContentTypesParser.php
Labels: 🐛 tag: bug fix

#2465 Don't break if listing pages have extra parameters
  src/Controller/Frontend/ListingController.php
Labels: 🐛 tag: bug fix

#2464 Show total number of records on listing
  templates/content/listing.html.twig
Labels: 🍏 low hanging fruit, 🧹 Chore

#2466 Prepare release 4.1.15
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2467 Update `simple.css` with latest changes
  public/theme/skeleton/css/simple.css
Labels: 🧹 Chore

#2473 Accept less strict search like `%foo%bar%`
  src/Repository/ContentRepository.php
Labels: 🐛 tag: bug fix

#2475 The `|excerpt` filter returns the excerpt in the correct locale
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#2476 Allow `--roles` option using the `bin/console bolt:add-user` command
  src/Command/AddUserCommand.php
Labels: tag: enhancement

#2477 Run migrations check on `composer install` and show how to migrate
  bin/composer-script/PostInstallScript.php
  bin/composer-script/PostUpdateScript.php
  bin/composer-script/Script.php
Labels: tag: enhancement

#2484 Fix GitHub action failed to install
  .github/workflows/behavioural_tests.yaml
Labels: topic: Tests, 🧹 Chore

#2485 Properly apply fix #2469 for master
  src/Controller/Frontend/ListingController.php
Labels: 🍏 low hanging fruit, 🐛 tag: bug fix

#2486 Fix the `allow_twig` option to work in the preview
  src/Controller/Backend/ContentEditController.php
  src/Entity/Field.php
  src/Event/Listener/FieldFillListener.php
Labels: 🐛 tag: bug fix

#2482 Redirect to homepage on authenticate if dashboard access is not granted
  src/Security/LoginFormAuthenticator.php
  tests/php/Security/LoginFormAuthenticatorTest.php
Labels: tag: enhancement, 🐛 tag: bug fix

#2491 Use form and shape in addition to colour for content statuses
  assets/scss/modules/base/_status.scss
Labels: Accessibility, tag: enhancement

#2492 Don't hide last ellipsis dot, search button covers input height
  assets/js/app/toolbar/Components/Toolbar.vue
  assets/scss/modules/admin/_toolbar.scss
Labels: tag: enhancement

#2495 Add `copy to clipboard` for suggested password. Fix view password glitch
  assets/js/app/editor/Components/Password.vue
  assets/scss/modules/user/user.scss
  templates/users/_form.html.twig
Labels: tag: enhancement

#2494 Localize content listing details
  assets/scss/modules/admin/_toolbar.scss
  templates/content/listing.html.twig
  translations/messages.bg.xlf
  translations/messages.en.xlf
Labels: tag: enhancement, topic: Multilingual 🌐

#2493 Pretty code tags in the Editor
  assets/scss/init/_base.scss
  assets/scss/init/_variables.scss
Labels: tag: enhancement

#2490 Minor mobile improvements to content editing
  assets/js/app/editor/Components/Image.vue
  assets/scss/modules/admin/_menupage.scss
  assets/scss/modules/admin/admin.scss
  templates/content/_buttons.html.twig
  templates/pages/menupage.html.twig
  tests/e2e/users.feature
Labels: tag: enhancement

#2497 Fixes a PHPStan check error, introduced in Symfony 5.2.6
  src/Command/ListUsersCommand.php
Labels: 🧹 Chore

#2499 On `Forbidden`, only redirect to the dashboard if the user is granted access to it. Otherwise show the `403`
  src/Controller/ErrorController.php
Labels: 🐛 tag: bug fix
