Repository bolt/core, pull requests merged in 2021-02, with the labels that each got.

#2350 Fix new checkbox value on existing records
  src/Entity/Content.php
Labels: 🐛 tag: bug fix

#2356 Remove (abandoned) `sensiolabs/security-checker`
  .github/workflows/code_analysis.yaml
  composer.json
  config/packages/security_checker.yaml
Labels: 🧹 Chore

#2361 Use TemplateSelect `filter` option with directories
  composer.json
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#2367 Fix e-mail address in github issue template
  .github/ISSUE_TEMPLATE/2_Security_issue.md
Labels: 🍏 low hanging fruit

#2363 Replace `and` with `&&`
  src/Configuration/Parser/ContentTypesParser.php
Labels: 🎩 refactor

#2357 Show an envelope icon for email fields to distinguish from text
  assets/js/app/editor/Components/Email.vue
Labels: tag: enhancement

#2362 Refactor `ErrorController` by replacing container dependency with `ParameterBagInterface`
  src/Controller/ErrorController.php
Labels: 🎩 refactor

#2364 Use PSR-1 basic coding standard for method names
  src/Controller/Backend/UserEditController.php
  src/Utils/FlagMaster.php
Labels: 🎩 refactor

#2370 Fix slow tests
  composer.json
  config/packages/test/security.yaml
  tests/e2e/login.feature
Labels: 🐛 tag: bug fix

#2374 Remove incorrect `PHPDoc @var` tag in RelationRepository
  src/Repository/RelationRepository.php
Labels: 🧹 Chore

#2371 Don't allow Path Traversal
  src/Controller/Backend/FileEditController.php
  src/Controller/Backend/FilemanagerController.php
  src/Utils/PathCanonicalize.php
Labels: topic: Security

#2373 Make multiselect fields iterable in Twig
  src/Entity/Field/CollectionField.php
  src/Entity/Field/FilelistField.php
  src/Entity/Field/ImagelistField.php
  src/Entity/Field/SelectField.php
  src/Entity/Field/SetField.php
  src/Entity/IterableFieldTrait.php
Labels: 🐛 tag: bug fix

#2375 Content `toArray()` method returns fields according to definition
  src/Entity/Content.php
Labels: 🎩 refactor

#2377 Fix date field with `required: true`
  assets/js/app/editor/Components/Date.vue
Labels: 🐛 tag: bug fix

#2379 Prepare release 4.2.0 beta 7
  assets/js/version.js
  composer.json
  package-lock.json
  package.json
  src/Version.php
  symfony.lock
Labels: 🧹 Chore

#2381 Prepare release 5.0.0 beta 1
  README.md
  assets/js/version.js
  composer.json
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2386 Ensure sufficient contrast ratio for Editor sidebar text
  assets/scss/modules/admin/_sidebar.scss
Labels: Accessibility

#2378 Keep cache timestamps for all `.env` files
  src/Configuration/Config.php
Labels: 🐛 tag: bug fix

#2385 Selects with `multiple: true` always have an array value
  src/Entity/Field/SelectField.php
Labels: 🐛 tag: bug fix

#2383 Make sure the magic `get` uses the configured `date_format`
  src/Utils/ContentHelper.php
Labels: 🐛 tag: bug fix

#2382 Fix `|order` filter by date
  src/Twig/ArrayExtension.php
Labels: 🐛 tag: bug fix

#2394 Keep `sensiolabs/security-checker` around for now
  composer.json
Labels: 🧹 Chore

#2396 Move `doctrine/doctrine-migrations-bundle` to `require-dev`
  composer.json
  package-lock.json
Labels: 🧹 Chore

#2397 Add Composer scripts for 4.2
  bin/composer-script/post-install-cmd.php
  bin/composer-script/post-update-cmd.php
  bin/composer-script/project-post-create-project-cmd.php
  bin/composer-script/project-post-install-cmd.php
  bin/composer-script/project-post-update-cmd.php
  bin/composer-script/project-pre-install-cmd.php
  bin/composer-script/project-pre-update-cmd.php
  bin/composer-script/run.php
Labels: 🎩 refactor

#2398 CS fixes
  bin/composer-script/post-install-cmd.php
  bin/composer-script/post-update-cmd.php
  bin/composer-script/project-post-create-project-cmd.php
  bin/composer-script/project-post-install-cmd.php
  bin/composer-script/project-post-update-cmd.php
  bin/composer-script/project-pre-update-cmd.php
  bin/composer-script/run.php
  package-lock.json
Labels: 🧹 Chore

#2399 Add `overview_aside` widget targets
  src/Widget/BaseWidget.php
  templates/content/listing.html.twig
Labels: tag: enhancement

#2408 Don't ignore locale settings on initial request or clear session
  src/Event/Subscriber/LocaleSubscriber.php
Labels: 🐛 tag: bug fix

#2407 Fix taxonomy `listing_template` inconsistency. Fix the canonical for `slug` and `singular_slug`
  src/Controller/Frontend/TaxonomyController.php
  src/TemplateChooser.php
Labels: 🐛 tag: bug fix

#2400 Don't show old fields in a `set` if they're removed from the definition
  src/Entity/Field/SetField.php
Labels: 🐛 tag: bug fix

#2416 Don't break collection looping if definition changes
  src/Event/Listener/FieldFillListener.php
Labels: 🐛 tag: bug fix

#2421 Allow for colored output in update scripts
  bin/composer-script/PostInstallScript.php
  bin/composer-script/PostUpdateScript.php
Labels: 🎩 refactor

#2420 Use `symfony/assets` URL generation for assets in `ImageExtension.php`
  src/Twig/ImageExtension.php
Labels: 🐛 tag: bug fix

#2419 Add project update/install callables
  bin/composer-script/ProjectEventHandler.php
Labels: 🎩 refactor

#2426 Don't use `dump` in setcontent tests
  public/theme/skeleton/custom/setcontent_1.twig
Labels: topic: Tests

#2422 From Library button on Windows generates the correct URL
  src/Controller/Backend/Async/FileListingController.php
Labels: 🐛 tag: bug fix

#2428 `|order` filter by negative number sorts correctly
  src/Twig/ArrayExtension.php
Labels: 🐛 tag: bug fix

#2425 Update npm dependencies
  package-lock.json
  package.json
Labels: dependencies

#2423 Allow `ROLE_EDITOR` to view and manage media files
  config/bolt/permissions.yaml
Labels: tag: enhancement

#2411 Remove `is_allowed` function. Symfony equivalent is `is_granted`
  src/Twig/UserExtension.php
Labels: 🎩 refactor

#2409 Refactor/remove unused parents check
  src/Configuration/Content/FieldType.php
Labels: 🎩 refactor

#2431 CS fixes, type hinting
  src/Api/Extensions/ContentExtension.php
  src/Command/ClearThumbnailCacheCommand.php
  src/Command/DeleteUserCommand.php
  src/Command/ExtensionsConfigureCommand.php
  src/Command/ExtensionsListCommand.php
  src/Command/ExtensionsServicesCommand.php
  src/Command/ExtensionsShowCommand.php
  src/Command/InfoCommand.php
  src/Command/ListUsersCommand.php
  src/Command/ResetPasswordCommand.php
  src/Command/ResetSecretCommand.php
  src/Command/SetupCommand.php
  src/Command/WelcomeCommand.php
  src/Configuration/FileLocation.php
  src/Controller/Backend/BulkOperationsController.php
  src/Controller/Backend/ResetPasswordController.php
  src/Controller/Backend/UserEditController.php
  src/Controller/Frontend/TemplateController.php
  src/DataFixtures/BaseFixture.php
  src/DataFixtures/UserFixtures.php
  src/Doctrine/Query/Cast.php
  src/Event/Subscriber/UserLocaleSubscriber.php
  src/Form/UserType.php
  src/Repository/ContentRepository.php
  src/Security/AdminApiVoter.php
  src/Security/AdminTranslateVoter.php
  src/Security/ContentOwnerVoter.php
  src/Security/ContentVoter.php
  src/Security/GlobalVoter.php
  src/Security/LoginFormAuthenticator.php
  src/Security/LogoutListener.php
  src/Security/SwitchUserVoter.php
  src/Storage/Filter.php
  src/Storage/QueryParameterParser.php
  src/Twig/CommonExtension.php
  src/Twig/DumpExtension.php
  src/Twig/JsonExtension.php
  src/Utils/FlagMaster.php
  src/Utils/Markdown.php
  src/Utils/Sanitiser.php
  src/Widget/Injector/QueueProcessor.php
Labels: 🧹 Chore

#2404 Remove direct references to fields from twig templates
  templates/_partials/fields/file.html.twig
  templates/_partials/fields/filelist.html.twig
  templates/_partials/fields/image.html.twig
  templates/_partials/fields/imagelist.html.twig
Labels: 🎩 refactor

#2445 Fixing broken XML
  translations/messages.en.xlf
Labels: 🧹 Chore
