Repository bolt/core, pull requests merged in 2021-05, with the labels that each got.

#2557 Require opt-in for FLoC header
  config/bolt/config.yaml
  src/Configuration/Parser/GeneralParser.php
  src/Event/Subscriber/WidgetSubscriber.php
  src/Widget/FlocOptOutHeader.php
Labels: new feature

#2566 Fix ecs breakage with `friendsofphp/php-cs-fixer`
  composer.json
Labels: 🧹 Chore

#2563 Copy packaged themes in `bolt:copy-themes` command
  src/Command/CopyThemesCommand.php
  src/Extension/ExtensionRegistry.php
Labels: 🐛 tag: bug fix

#2576 Several fixes for handling Relations
  config/bolt/contenttypes.yaml
  src/Configuration/Parser/ContentTypesParser.php
  src/Controller/Backend/ContentEditController.php
  src/Factory/RelationFactory.php
Labels: 🐛 tag: bug fix

#2577 Fields can be sanitised without external dependencies
  config/services.yaml
  src/Entity/ContentExtrasTrait.php
  src/Entity/Field.php
  src/Kernel.php
  yaml-migrations/m_2021-05-11-services.yaml
Labels: 🎩 refactor

#2567 Update LICENSE
  LICENSE
Labels: 🧹 Chore

#2583 Renaming files for consistency
  yaml-migrations/m_2021-01-15-doctrine.yaml
  yaml-migrations/m_2021-03-14-permissions.yaml
Labels: 🧹 Chore

#2584 Fix copy-themes with packages. Implement copying specific theme
  src/Command/CopyThemesCommand.php
  src/Extension/ExtensionRegistry.php
Labels: 🎩 refactor, 🐛 tag: bug fix

#2585 Autowire twig environment to Field for rendering
  src/Entity/Content.php
  src/Entity/Field.php
  src/Event/Listener/ContentFillListener.php
  src/Kernel.php
Labels: 🎩 refactor, 🐛 tag: bug fix

#2587 Fix breaking kernel and create new `EntityServiceProvider`
  config/services.yaml
  src/Controller/Backend/ContentEditController.php
  src/Entity/Content.php
  src/Entity/Field.php
  src/Event/Listener/ContentFillListener.php
  src/Event/Subscriber/EntityServiceProvider.php
  src/Kernel.php
  src/Twig/ContentExtension.php
  src/Twig/FrontendMenuExtension.php
  yaml-migrations/m_2021-05-11-services.yaml
Labels: 🎩 refactor

#2594 Maintenance badge has `z-index: 999999;` so that it is visible above other content
  templates/widget/maintenance_mode.twig
Labels: tag: enhancement

#2597 Performance boost: Keep in-memory copy of `currentLocale`
  src/Utils/LocaleHelper.php
Labels: 🐛 tag: bug fix
