Repository bolt/core, pull requests merged in 2021-06, with the labels that each got.

#2603 Fix `|filter` and `|order` chaining returning no results
  src/Twig/ArrayExtension.php
Labels: 🐛 tag: bug fix

#2605 Update Symfony to 5.3
  composer.json
  src/Controller/Backend/UserEditController.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
Labels: 🧹 Chore

#2607 Cleanup of Symplify dependencies
  composer.json
  config/bundles.php
Labels: 🧹 Chore

#2614 Add restriction for (global) Composer 2 to `composer.json`
  composer.json
Labels: topic: DX

#2611 Adding Jasny Twig Extensions for Bolt 5.
  composer.json
  config/services.yaml
  symfony.lock
  yaml-migrations/m_2021-06-04-services.yaml
Labels: new feature

#2619 Fix `maximum_listing_select` in `config.yaml`
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#2618 `extensions:configure` accepts both `.yaml` and `.yml` for config, routes and services in extensions
  src/Command/ExtensionsConfigureCommand.php
Labels: 🐛 tag: bug fix

#2623 Fix error in custom code producing seemingly unrelated message. Catch `LoaderLoadException` instead of `Throwable`
  src/Kernel.php
Labels: 🐛 tag: bug fix

#2628 Pass around `BaseExtension` instead of string in `ExtensionsConfigureCommand`
  src/Command/ExtensionsConfigureCommand.php
Labels: 🐛 tag: bug fix

#2630 Add `ignore_empty` option in `query_search` listing filtering
  config/bolt/config.yaml
  src/Configuration/Parser/GeneralParser.php
  src/Controller/Frontend/ListingController.php
Labels: new feature

#2625 Add cypress tests
  .github/workflows/cypress_tests.yaml
  cypress.json
  package-lock.json
  package.json
  tests/cypress/integration/backend_api.spec.js
  tests/cypress/plugins/index.js
  tests/cypress/support/index.js
  tests/e2e/backend_api.feature
Labels: topic: Tests

#2634 Use `nelexa/zip` 3.4, because it supports both PHP 7.2 and 8.0
  composer.json
Labels: 🧹 Chore

#2640 Don't allow `symfony/security-http` 5.3.0 and 5.3.1
  composer.json
Labels: topic: Security

#2639 Adding missing methods to ExtensionInterface and BaseExtension
  src/Extension/BaseExtension.php
  src/Extension/ExtensionInterface.php
Labels: 🎩 refactor

#2638 Decouple directive handling from the `ContentQueryParser`
  src/Storage/ContentQueryParser.php
  src/Storage/Directive/DirectiveHandler.php
  src/Storage/FrontendQueryScope.php
Labels: 🎩 refactor

#2644 Fix cypress login with correct Bolt 5 inputs
  tests/cypress/support/index.js
Labels: topic: Tests

#2652 Warn editors for unsaved changes only if there are changes to content
  assets/js/app/editor/unsavedchanges.js
Labels: tag: enhancement

#2650 Remove unneeded line and fix rogue quote
  .env
Labels: 🍏 low hanging fruit

#2651 Allows running `bin/console` from other folders than just ProjectDir
  src/Command/InfoCommand.php
Labels: 🐛 tag: bug fix

#2654 Clean up composer.json, remove `roave/security-advisories`
  composer.json
  symfony.lock
Labels: 🧹 Chore

#2655 Prepare release 5.0.0-beta.10
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2656 Use `localdate`, in preparation of this being the standard in 5.0
  public/theme/skeleton/partials/_recordfooter.twig
Labels: 🍏 low hanging fruit
