Repository bolt/core, pull requests merged in 2021-01, with the labels that each got.

#2276 Replace (abandoned) `peterkahl/country-code-to-emoji-flag` package with fork
  composer.json
  src/Utils/FlagMaster.php
  src/Utils/LocaleHelper.php
Labels: 🧹 Chore

#2277 Prepare release 4.1.10
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2287 Feature/maxlength pattern textarea #2284
  assets/js/app/editor/Components/Textarea.vue
  src/Configuration/Content/FieldType.php
  templates/_partials/fields/_base.html.twig
  templates/_partials/fields/textarea.html.twig
  tests/php/Configuration/Parser/ContentTypesParserTest.php
Labels: new feature

#2289 Fix allow twig and deprecate `record|allow_twig` requirement
  src/Entity/Field.php
  src/Event/Listener/ContentFillListener.php
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#2281 Show number of records on listing
  templates/content/listing.html.twig
Labels: new feature

#2280 Allow `id` in sanitiser (purifier). Don't sanitise fields with `sanitise: false`
  src/Event/Listener/FieldFillListener.php
  src/Utils/Sanitiser.php
Labels: 🐛 tag: bug fix

#2283 Remove select tag space
  assets/scss/modules/editor/fields/_multiselect.scss
Labels: 🐛 tag: bug fix

#2291 Remove reference to paragonie
  composer.json
Labels: dependencies, 🧹 Chore

#2245 [WIP] Versioned project update
  .gitattributes
  bin/composer-script/project-post-create-project-cmd.php
  bin/composer-script/project-post-install-cmd.php
  bin/composer-script/project-post-update-cmd.php
  bin/composer-script/project-pre-update-cmd.php
  bin/composer-script/run.php
  migrations/Version20201210105836.php
  yaml-migrations/m_2021-01-06-doctrine_migrations.yaml
Labels: Project, new feature

#2293 Preparing 4.2.0-beta.4
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2295 Versioned project update
  composer.json
  yaml-migrations/m_2021-01-07-reset_password.yaml
Labels: tag: enhancement

#2296 Fix `default` option for select field
  src/Entity/Field/SelectField.php
Labels: 🐛 tag: bug fix

#2297 Make sure Other Content works on mobile
  src/Menu/BackendMenuBuilder.php
Labels: 🐛 tag: bug fix

#2290 Fix casting exception with`orderby` when using MySQL/PostgreSQL
  src/Doctrine/Query/Cast.php
  src/Storage/Directive/OrderDirective.php
Labels: 🐛 tag: bug fix

#2303 Use Symfony's HTTPClient instead of Guzzle
  src/DataFixtures/ImageFetchFixtures.php
Labels: 🎩 refactor

#2304 Reach backend edit by prepending `/bolt/edit/` to current page's URL
  src/Controller/Backend/ContentEditController.php
Labels: new feature

#2301 Run bolt in a11y tests
  .github/workflows/a11y_tests.yaml
  package.json
  tests/a11y/README.md
  tests/a11y/pa11yci.json
Labels: topic: Tests

#2309 Warn editors for unsaved changes to content
  assets/js/app/editor/index.js
  assets/js/app/editor/unsavedchanges.js
Labels: new feature

#2308 Open secure link new tab
  templates/content/_buttons.html.twig
Labels: tag: enhancement

#2310 Fix setcontent query for checkbox `false` values
  src/Storage/QueryParameterParser.php
Labels: 🐛 tag: bug fix

#2312 Prepare release 4.2.0-beta.5
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2315 Fix phpstan 0.12.67 failing on `Cannot instantiate interface Bolt\Entity\FieldInterface`
  src/Event/Listener/FieldDiscriminatorListener.php
Labels: topic: Tests

#2313 Use default locale when not explicitly stated
  src/Event/Subscriber/LocaleSubscriber.php
Labels: 🐛 tag: bug fix

#2322 Don't require user to re-authenticate after changing user locale
  src/Controller/Backend/ProfileController.php
  src/Event/Subscriber/LocaleSubscriber.php
  src/Event/Subscriber/UserLocaleSubscriber.php
Labels: 🐛 tag: bug fix

#2320 Migrate `JSON_GET_TEXT` and `CAST` in `doctrine.yaml` since 4.1.11
  yaml-migrations/m_2021_01_15-doctrine.yaml
Labels: 🚸 Migration

#2321 Invite Bolters to join people.boltcms.io
  src/Command/WelcomeCommand.php
Labels: tag: enhancement

#2217 Issue 2215 searchable select
  templates/_partials/fields/select.html.twig
Labels: Topic: Third Party 🖇

#2326 Redirect to Bolt Dashboard if 403 response comes from the Editor
  src/Controller/ErrorController.php
Labels: tag: enhancement

#2325 Bolt generates pretty URLs without `contentTypeSlug` in path or query params
  src/Canonical.php
Labels: new feature

#2336 Pin API-platform to `2.5.*` for now
  composer.json
Labels: 🧹 Chore

#2333 Fix YouTube oEmbed missing `title` accessibility issue
  src/Controller/Backend/Async/EmbedController.php
Labels: Accessibility, 🐛 tag: bug fix

#2334 Clear config cache on `bin/console cache:clear`
  src/Configuration/Config.php
  src/Event/ConfigCacheClearer.php
Labels: 🐛 tag: bug fix

#2339 Prepare Release 4.1.12
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2340 Prepare relase 4.2.0-beta.6
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2345 Fix `|svg` filter for images outside of set
  src/Twig/ImageExtension.php
Labels: 🐛 tag: bug fix

#2347 Fix `record|thumbnail` getting different image than `record|image`
  src/Twig/ImageExtension.php
Labels: 🐛 tag: bug fix

#2348 Forbid certain theme files from public exposure
  public/.htaccess
Labels: topic: Security

#2349 New Skeleton theming
  public/theme/skeleton/css/new.css
  public/theme/skeleton/css/simple.css
  public/theme/skeleton/index.twig
  public/theme/skeleton/partials/_aside.twig
  public/theme/skeleton/partials/_footer.twig
  public/theme/skeleton/partials/_header.twig
  public/theme/skeleton/partials/_image.twig
  public/theme/skeleton/partials/_master.twig
  public/theme/skeleton/partials/_recordfooter.twig
  public/theme/skeleton/partials/_sub_menu_header.twig
Labels: theme, 🎩 refactor
