Repository bolt/core, pull requests merged in 2021-08, with the labels that each got.

#2737 Fix `group: sidebar` conflicting with Bolt's sidebar
  assets/js/app/sidebar/index.js
  templates/_base/layout.html.twig
  tests/e2e/record_listing.feature
Labels: 🐛 tag: bug fix

#2742 Throw 404 response when thumbnailing a missing image
  src/Controller/ImageController.php
Labels: 🐛 tag: bug fix

#2743 `imagelist` and `filelist` fields can be emptied
  assets/js/app/editor/Components/Filelist.vue
  assets/js/app/editor/Components/Imagelist.vue
  src/Entity/Field/FilelistField.php
  src/Entity/Field/ImagelistField.php
Labels: 🐛 tag: bug fix

#2744 Run `bin/console bolt:reset-secret` when creating a new project
  bin/composer-script/CreateProjectScript.php
Labels: topic: Security

#2745 Update the warning color to a11y compatible
  assets/scss/init/_variables.scss
Labels: Accessibility

#2749 Create a new readme
  README.md
  SETUP.md
Labels: 🧹 Chore

#2738 Fix tests following `sidebar` rename to `bolt--sidebar`
  tests/cypress/integration/record_listing.spec.js
Labels: 🐛 tag: bug fix

#2747 Exclude partials in the `templateselect` default filter. Move methods to `FieldExtension`
  src/Twig/ContentExtension.php
  src/Twig/FieldExtension.php
Labels: 🎩 refactor, 🐛 tag: bug fix

#2754 Improve feedback for uploading files
  src/Configuration/Config.php
  templates/finder/_uploader.html.twig
  templates/pages/about.html.twig
Labels: topic: UX

#2755 Use Symfony Process component instead of `passthru`
  bin/composer-script/Script.php
Labels: 🐛 tag: bug fix

#2762 Re-add method that went missing somehow
  bin/composer-script/Script.php
Labels: 🐛 tag: bug

#2761 Update asset dependencies
  package-lock.json
  package.json
Labels: dependencies

#2759 Improve accessibility names, ids and labels
  assets/js/app/editor/Components/File.vue
  assets/js/app/editor/Components/Image.vue
  assets/js/app/editor/Components/Text.vue
  assets/scss/init/_variables.scss
  templates/_partials/fields/_base.html.twig
  templates/content/_buttons.html.twig
  templates/finder/editfile.html.twig
  templates/pages/logviewer.html.twig
  tests/a11y/pa11yci.json
  tests/cypress/integration/edit_record_1_content.spec.js
  tests/cypress/integration/edit_record_1_fill_set_collection.spec.js
Labels: Accessibility

#2760 Add helpful notice to 404 exception page
  templates/helpers/page_404.html.twig
Labels: topic: DX

#2764 Prepare release 4.2.1
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2767 Search now also finds words with special characters, like `büßen`
  src/Repository/ContentRepository.php
Labels: 🐛 tag: bug fix

#2772 Fix preview button (if complaining about GET vs POST)
  src/Controller/TwigAwareController.php
Labels: 🐛 tag: bug fix

#2789 Fix `optionsLimit` hyphenation warning
  assets/js/app/editor/Components/Select.vue
Labels: 🎩 refactor, 🧹 Chore

#2769 Prepare release 4.2.2
  CHANGELOG.md
  package.json
  src/Version.php
Labels: 🧹 Chore

#2788 Preview is frontend zone, fix for viewing content in another locale
  src/Controller/Backend/ContentEditController.php
  src/Controller/Frontend/PreviewController.php
  src/Controller/TwigAwareController.php
Labels: 🐛 tag: bug fix

#2787 Remove `copyEnv` from `post-create-project` script
  bin/composer-script/CreateProjectScript.php
Labels: 🎩 refactor

#2779 Improving Installation Commands
  src/Command/AddUserCommand.php
  src/Command/ClearThumbnailCacheCommand.php
  src/Command/CopyThemesCommand.php
  src/Command/DeleteUserCommand.php
  src/Command/ExtensionsConfigureCommand.php
  src/Command/ExtensionsListCommand.php
  src/Command/ExtensionsServicesCommand.php
  src/Command/ExtensionsShowCommand.php
  src/Command/InfoCommand.php
  src/Command/ListUsersCommand.php
  src/Command/ResetSecretCommand.php
  src/Command/SetupCommand.php
  src/Command/WelcomeCommand.php
Labels: topic: DX

#2770 Create `bin/console server` command, to easily start webserver
  src/Command/ServerCommand.php
Labels: new feature, topic: DX

#2802 CS fixes in `fix-bundles.php`
  bin/fix-bundles.php
Labels: 🧹 Chore

#2803 Add `--full-path` option to `bolt:server` command
  src/Command/ServerCommand.php
  src/Command/SetupCommand.php
Labels: topic: DX
