Repository bolt/core, pull requests merged in 2021-09, with the labels that each got.

#2823 Show `memory_limit` and attempt to set in on CLI
  bin/console
  phpstan.neon
  src/Command/ImageTrait.php
  src/Command/InfoCommand.php
  src/Controller/Backend/GeneralController.php
  templates/pages/about.html.twig
Labels: topic: DX

#2828 Fix querying selects and multiselects
  config/packages/doctrine.yaml
  src/Doctrine/Version.php
  src/Storage/FieldQueryUtils.php
  src/Storage/SelectQuery.php
  yaml-migrations/m_2021-09-16-doctrine.yaml
Labels: 🐛 tag: bug fix

#2812 Don't break `printquery` on array values
  composer.json
  src/Storage/Directive/PrintQueryDirective.php
Labels: 🐛 tag: bug fix

#2830 Prepare release 5.0.2
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2844 Fix `{% setcontent where { … } %}` for Checkbox fields
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#2846 Fix Multiselect in setcontent
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix
