Repository bolt/core, pull requests merged in 2021-11, with the labels that each got.

#2900 Fix UX issue #2899
  templates/_partials/fields/_label.html.twig
Labels: 🐛 tag: bug fix, topic: UX

#2907 Ensure consistency in sluggified anchor link
  templates/content/edit.html.twig
Labels: 🐛 tag: bug fix

#2908 Block active sessions from disabled users
  src/Security/GlobalVoter.php
Labels: 🐛 tag: bug fix, topic: Security

#2914 Log `TokenDeauthenticatedEvent` in Bolt logger
  src/Security/TokenDeauthenticatedSubscriber.php
Labels: tag: enhancement

#2913 More detailed logging when logging in and logging out
  src/Security/LoginFormAuthenticator.php
  src/Security/LogoutListener.php
Labels: tag: enhancement

#2904 Redirect 'GET on Preview' link to edit page
  src/Controller/Frontend/PreviewController.php
Labels: 🍏 low hanging fruit

#2915 Don't fail on upsert or create if programatically creating content without authentication
  src/Factory/ContentFactory.php
Labels: 🐛 tag: bug fix

#2919 Fix unique slugs if title is empty
  src/Event/Listener/ContentFillListener.php
Labels: 🐛 tag: bug fix

#2929 Allow overriding field twig templates
  templates/content/_fields.html.twig
Labels: new feature

#2925 Fix the postfix css
  assets/scss/modules/editor/fields/_pre_postfix.scss
Labels: topic: UX

#2926 Fix the Other Content menu icon
  src/Menu/BackendMenuBuilder.php
Labels: 🐛 tag: bug fix, topic: UX

#2912 Multiple sessions reflect correctly in the `Current sessions` area
  config/packages/security.yaml
  src/Entity/User.php
  src/Entity/UserAuthToken.php
  src/Security/LoginFormAuthenticator.php
  src/Security/LogoutListener.php
  templates/users/listing.html.twig
  tests/php/Security/LoginFormAuthenticatorTest.php
Labels: 🧨 breaking change, 🐛 tag: bug fix

#2947 Create a new `error` request zone
  src/Controller/ErrorController.php
  src/Controller/ErrorZoneInterface.php
  src/Event/Subscriber/ZoneSubscriber.php
  src/Widget/Injector/RequestZone.php
Labels: tag: enhancement

#2951 Remove behat
  .github/workflows/behavioural_tests.yaml
  Makefile
  behat.yml
  composer.json
  config/bundles.php
  config/services_test.yaml
  symfony.lock
  templates/pages/about.html.twig
  tests/api/get_content.feature
  tests/api/get_content_fields.feature
  tests/behat/bootstrap/ApiContext.php
  tests/behat/bootstrap/CommonContext.php
Labels: topic: Tests, dependencies, 🧹 Chore

#2958 Refactor dependency for `csrfTokenManager` service
  src/Controller/Backend/Async/EmbedController.php
  src/Controller/Backend/Async/UploadController.php
  src/Controller/Backend/BulkOperationsController.php
  src/Controller/Backend/ContentEditController.php
  src/Controller/Backend/FileEditController.php
  src/Controller/Backend/FilemanagerController.php
  src/Controller/Backend/MediaEditController.php
  src/Controller/CsrfTrait.php
  src/Controller/Frontend/PreviewController.php
Labels: 🎩 refactor

#2965 Fix content jumping when selecting a value from select
  assets/scss/modules/editor/fields/_multiselect.scss
Labels: 🐛 tag: bug fix

#2964 Fix contenlisting sample route
  config/routes.yaml
Labels: 🐛 tag: bug fix

#2957 Toggle cache for related options
  config/bolt/config.yaml
  config/services.yaml
  src/Cache/CachingInterface.php
  src/Cache/CachingTrait.php
  src/Cache/RelatedOptionsUtilityCacher.php
  src/Twig/RelatedExtension.php
  src/Utils/RelatedOptionsUtility.php
  yaml-migrations/m_2021-11-22-services.yaml
Labels: tag: enhancement, 🎩 refactor

#2963 Drop `UNIQUE` constraint for bolt_user_auth_token.user_id
  migrations/Version20211123103530.php
Labels: 🚸 Migration

#2977 Fix getting db version (lock `doctrine/dbal`)
  composer.json
Labels: dependencies

#2648 Role-based API support for `POST`, `PUT` and `DELETE` operations
  config/bolt/permissions.yaml
  config/packages/security.yaml
  config/services.yaml
  src/Api/ContentDataPersister.php
  src/Entity/Content.php
  src/Entity/Field.php
  src/Entity/Field/CollectionField.php
  src/Entity/Field/SetField.php
  src/Entity/Relation.php
  tests/cypress/integration/api_getcontent.spec.js
  yaml-migrations/m_2021-11-23-security.yaml
  yaml-migrations/m_2021-11-23-services.yaml
Labels: new feature
