Repository bolt/core, pull requests merged in 2021-12, with the labels that each got.

#2992 Fix phpunit FrontendMenu test
  composer.json
Labels: 🐛 tag: bug fix, 🧹 Chore

#2991 Create meaningful fixtures for geolocation fields
  src/DataFixtures/ContentFixtures.php
Labels: 🐛 tag: bug fix

#2994 Add new paginate function for arrays
  src/Twig/ArrayExtension.php
Labels: new feature

#2995 Allow Select fields with `JSON_SEARCH` to filter multiple values
  src/Storage/SelectQuery.php
Labels: 🐛 tag: bug fix

#2999 Cleanup `todo` comments
  assets/js/services/api/content.js
  templates/pages/about.html.twig
  templates/users/profile.html.twig
Labels: 🧹 Chore

#3005 Fallback to Symfony's default public path for bundles
  config/services.yaml
  src/Twig/AssetsExtension.php
  yaml-migrations/m_2021-12-10-services.yaml
Labels: 🐛 tag: bug fix

#3007 Implement the new Symfony Security Component
  config/packages/security.yaml
  src/Event/Subscriber/AuthSubscriber.php
  src/Security/LoginFormAuthenticator.php
  src/Security/LogoutListener.php
  tests/php/Security/LoginFormAuthenticatorTest.php
Labels: tag: enhancement, 🎩 refactor, topic: Security

#3015 Fix php unit relation test
  bin/composer-script/CorePostUpdateScript.php
Labels: topic: Tests

#3014 Redirect to login page if unauthenticated
  config/packages/security.yaml
  phpstan.neon
  src/Security/AuthenticationEntryPointRedirector.php
  templates/security/login.html.twig
  yaml-migrations/m_2021-12-10-security_1.yaml
Labels: 🐛 tag: bug fix

#3017 Port the has sortorder for taxonomies 3001 (#3016)
  config/bolt/permissions.yaml
  public/theme/skeleton/custom/setcontent_1.twig
  src/Controller/Backend/ContentEditController.php
  src/DataFixtures/UserFixtures.php
  src/Doctrine/Version.php
  src/Storage/Directive/OrderDirective.php
  src/Storage/FieldQueryUtils.php
  src/Twig/ContentExtension.php
  templates/_macro/_macro.html.twig
  templates/content/_taxonomies.html.twig
  tests/cypress/cypress-dev.json
  tests/cypress/integration/chief_editor_permissions.spec.js
  tests/cypress/integration/setcontent.spec.js
Labels: 🐛 tag: bug fix

#3018 Add curl API tests
  .github/workflows/api_tests.yaml
Labels: topic: API, topic: Tests

#3028 Make `LoginFormAuthenticator` compatible with Symfony 5.3
  src/Security/LoginFormAuthenticator.php
Labels: ☣️ critical, 🐛 tag: bug fix

#3029 Composer 2.2 compatibility fix
  composer.json
Labels: 🧹 Chore
