Repository bolt/core, pull requests merged in 2021-04, with the labels that each got.

#2500 Only show generic `Invalid credentials` error if error is credentials related
  src/Security/LoginFormAuthenticator.php
Labels: tag: enhancement, topic: Security

#2501 Tweaking users and permissions
  config/bolt/permissions.yaml
  config/packages/security.yaml
  src/Command/AddUserCommand.php
  src/Command/SetupCommand.php
  src/DataFixtures/UserFixtures.php
  src/Security/SwitchUserVoter.php
  templates/users/listing.html.twig
  tests/e2e/login.feature
  tests/e2e/users.feature
  tests/php/Repository/UserRepositoryTest.php
Labels: 🧹 Chore

#2506 Create SECURITY.md
  SECURITY.md
Labels: 🧹 Chore

#2505 Don't keep the date field buttons focused after clicking
  assets/js/app/editor/Components/Date.vue
Labels: 🐛 tag: bug fix

#2507 Use `CompletePackageInterface` in BaseExtension
  src/Extension/BaseExtension.php
  src/Extension/ExtensionInterface.php
Labels: 🐛 tag: bug fix

#2509 Fix typehinting `PathExpression` -> `Node` for property
  src/Doctrine/Query/Cast.php
Labels: 🧹 Chore

#2410 Remove 4.x deprecations
  composer.json
  public/theme/skeleton/partials/_recordfooter.twig
  src/Controller/TwigAwareController.php
  src/Event/UserEvent.php
  src/Extension/BaseExtension.php
  src/Twig/ContentExtension.php
  src/Twig/LocaleExtension.php
  src/Twig/TranslatableExtension.php
  templates/content/_fields.html.twig
  templates/helpers/_field_blocks.twig
Labels: 🎩 refactor, 🧹 Chore

#2511 Make sure a select field can accept a string value
  src/Entity/Field/SelectField.php
Labels: 🐛 tag: bug fix

#2515 Fix bug where `anyField` search no longer works on listing
  src/Controller/Frontend/ListingController.php
Labels: 🐛 tag: bug fix

#2517 Assert User's email is not blank
  src/Entity/User.php
Labels: 🐛 tag: bug fix

#2518 Allow parsing of `localdate`s like `now` or `today + 1 week, 21:00`
  src/Twig/LocaleExtension.php
Labels: 🐛 tag: bug fix

#2520 Suppress unneeded notices in ECS
  ecs.php
Labels: 🐛 tag: bug fix

#2521 Don't run migrations in composer scripts, if the Database is not initialised yet.
  bin/composer-script/CreateProjectScript.php
  bin/composer-script/PostInstallScript.php
  bin/composer-script/PostUpdateScript.php
  bin/composer-script/PrePackageUninstallScript.php
  bin/composer-script/ProjectEventHandler.php
  bin/composer-script/Script.php
  src/Command/InfoCommand.php
Labels: topic: DX

#2522 Initialise Doctrine Migration table, make command less noisy
  Makefile
  src/Command/SetupCommand.php
Labels: topic: DX, topic: UX

#2523 Show `404` instead of Exception when missing secret
  src/Controller/Frontend/DetailController.php
Labels: 🐛 tag: bug fix

#2525 Release/5.0.0 beta.5
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2529 Decode HTML entities in `title_format` and related
  composer.json
  src/Utils/ContentHelper.php
Labels: 🐛 tag: bug fix

#2534 Improve backend search box accessibility
  assets/js/app/toolbar/Components/Toolbar.vue
  templates/_base/layout.html.twig
Labels: Accessibility, tag: enhancement

#2533 Improve contrast ratio in filemanager
  templates/finder/_files_list.html.twig
Labels: Accessibility, tag: enhancement

#2537 Allow `SelectField` options from callables and services
  src/Entity/Field/SelectField.php
  src/Kernel.php
  src/Twig/ContentExtension.php
Labels: new feature

#2532 Locale get link always `_locale` parameter
  src/Utils/LocaleHelper.php
Labels: 🐛 tag: bug fix

#2539 Fix datepicker to only attempt to use existing locales, ensuring Time Picking still works
  templates/_partials/fields/date.html.twig
Labels: 🐛 tag: bug fix

#2542 Fix edgecase where Excerpt could start with `. `.
  src/Twig/ContentExtension.php
Labels: 🐛 tag: bug fix

#2541 The `latest` directive uses `-publishedAt` instead of `-id`
  public/theme/skeleton/custom/setcontent_1.twig
  src/Storage/Directive/LatestDirectiveHandler.php
Labels: 🐛 tag: bug fix

#2543 Prepare release 4.1.18
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
Labels: 🧹 Chore

#2549 Don't throw `Argument 2 passed to Bolt\Doctrine\JsonHelper::wrapJsonFunction()` for checkboxes
  src/Doctrine/JsonHelper.php
Labels: 🐛 tag: bug fix

#2548 Support multiple targets for widget, keeping `$target` too
  src/Widget/BaseWidget.php
  src/Widget/BoltHeaderWidget.php
  src/Widget/Injector/HtmlInjector.php
  src/Widget/ResponseTrait.php
  src/Widget/SnippetWidget.php
  src/Widget/WidgetInterface.php
  src/Widgets.php
  tests/php/Widget/WidgetsTest.php
Labels: new feature

#2554 Fix a CSS quirk in listing overview pages
  assets/scss/modules/listing/row/row.scss
Labels: 🐛 tag: bug fix
