Repository bolt/core, pull requests merged in 2022-01, with the labels that each got.

#3044 Typehint QuestionHelper (make PhpStan happy)
  README.md
  src/Command/WelcomeCommand.php
Labels: 🧹 Chore

#3042 Fixing logo alt
  README.md
Labels: 🍏 low hanging fruit, 🧹 Chore

#3043 Fix Romanian transliteration
  assets/js/filters/string.js
Labels: topic: Multilingual 🌐

#3052 Bugfix Fix `maximum_listing_select` in `config.yaml` for Relation
  src/Twig/RelatedExtension.php
Labels: 🐛 tag: bug fix

#3053 Prepare release 5.1.2
  .github/workflows/unit_tests.yaml
  CHANGELOG.md
  phpstan.neon
  src/Version.php
Labels: 🧹 Chore

#3058 Set default `values` in FieldType
  src/Configuration/Content/FieldType.php
  tests/php/Configuration/Parser/ContentTypesParserTest.php
Labels: 🐛 tag: bug fix

#3061 Remove ignore of false positive in PHPStan
  phpstan.neon
Labels: 🧹 Chore

#3068 Fix configuration values not resolving correctly
  src/Configuration/Config.php
Labels: 🐛 tag: bug fix
