Repository bolt/core, pull requests merged in 2022-03, with the labels that each got.

#3109 Tiny fix, as per PHPStan
  src/Form/LoginType.php
Labels: 🧹 Chore

#3119 Bugfix: verify setting correct tags for caching works correctly
  src/Cache/CachingTrait.php
  src/Cache/SelectOptionsCacher.php
Labels: 🐛 tag: bug fix

#3134 Prepare release 5.1.5
  CHANGELOG.md
  assets/js/version.js
  package-lock.json
  package.json
  src/Version.php
  symfony.lock
Labels: 🧹 Chore

#3136 Don't break `/bolt/api/` if it's set to public and it's accessed in a browser
  config/packages/api_platform.yaml
  src/Entity/Content.php
  src/Menu/BackendMenu.php
  templates/_base/layout.html.twig
Labels: topic: API, 🐛 tag: bug fix

#3145 Ensure correct links in menu, when changing `backend_url` in `services.yaml`
  config/services.yaml
  src/Menu/BackendMenu.php
Labels: 🐛 tag: bug fix

#3152 Translation of missing German translations 🇩🇪
  translations/messages.de.xlf
  translations/security.de.xlf
  translations/validators.de.xlf
Labels: topic: Multilingual 🌐

#3156 Update Dutch translations 🇳🇱
  translations/messages.en.xlf
  translations/messages.nl.xlf
  translations/security.nl.xlf
  translations/validators.nl.xlf
Labels: topic: Multilingual 🌐
